#!/usr/bin/env node

/**
 * sync-wiki.mjs — Generate Wiki pages from repository documentation.
 *
 * Part of the Evolith CI strategy:
 *   - Runs in pre-push hook ONLY when documentation files change
 *   - Generates reference/wiki/*.md from existing repo docs (idempotent)
 *   - Does NOT push to GitHub Wiki (handled by GitHub Actions)
 *   - Follows the same mode detection as ci-runner.mjs
 *
 * Usage:
 *   node .harness/scripts/sync-wiki.mjs          # auto-detect changes
 *   node .harness/scripts/sync-wiki.mjs --force   # regenerate all pages
 *   node .harness/scripts/sync-wiki.mjs --check   # check if wiki is stale
 */

import fs from "node:fs";
import path from "node:path";
import { createHash } from "node:crypto";

const root = process.cwd();
const wikiDir = path.join(root, "reference", "wiki");
const fingerprintFile = path.join(wikiDir, ".fingerprint");

// ─── Source files ──────────────────────────────────────────────────────────────

const WIKI_SOURCES = {
  "Home.md": {
    files: ["README.md"],
    transform: transformHome,
  },
  "Getting-Started.md": {
    files: [
      "product/products/smart-cli/README.md",
      "product/products/mcp-services/README.md",
    ],
    transform: transformGettingStarted,
  },
  "Architecture.md": {
    files: [
      "reference/core/architecture/README.md",
      "reference/core/architecture/topologies/README.md",
    ],
    transform: transformArchitecture,
  },
  "Products.md": {
    files: [
      "product/products/smart-cli/README.md",
      "product/products/mcp-services/README.md",
      "product/products/core-api/README.md",
    ],
    transform: transformProducts,
  },
  "Governance.md": {
    files: [
      "reference/core/sdlc/standards/README.md",
      "reference/core/sdlc/README.md",
      "reference/core/control-center/gaps/gap-tracking.md",
    ],
    transform: transformGovernance,
  },
  "Contributing.md": {
    files: ["CONTRIBUTING.md"],
    transform: transformContributing,
  },
};

// ─── Transformers ──────────────────────────────────────────────────────────────

function readFileSafe(relativePath) {
  const full = path.join(root, relativePath);
  if (!fs.existsSync(full)) return "";
  return fs.readFileSync(full, "utf-8");
}

function extractSection(content, heading, level = 2) {
  const regex = new RegExp(
    `^#{${level}}\\s+${escapeRegex(heading)}\\s*$`,
    "m"
  );
  const match = content.match(regex);
  if (!match) return "";
  const start = match.index;
  const nextHeading = content.slice(start + match[0].length).match(
    new RegExp(`^#{1,${level}}\\s+`, "m")
  );
  const end = nextHeading
    ? start + match[0].length + nextHeading.index
    : content.length;
  return content.slice(start, end).trim();
}

function escapeRegex(str) {
  return str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function stripBilingualNav(content) {
  return content
    .replace(/^>\s*\*\*Bilingual.*?\*\*.*$/gm, "")
    .replace(/^>\s*\*\*Navegación.*?\*\*.*$/gm, "")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

function addWikiHeader(title, description) {
  return `# ${title}

> Auto-generated from repository documentation. Do not edit directly.
> Source: [github.com/beyondnetcode/evolith_arch32](https://github.com/beyondnetcode/evolith_arch32)

---

${description}

---

`;
}

function addWikiFooter(pageName) {
  const relatedPages = Object.keys(WIKI_SOURCES)
    .filter(f => f !== pageName + ".md")
    .map(f => {
      const name = f.replace(".md", "");
      const label = name.replace(/-/g, " ");
      return "- [" + label + "](https://github.com/beyondnetcode/evolith_arch32/wiki/" + name + ")";
    })
    .join("\n");
  const today = new Date().toISOString().split("T")[0];
  return "\n\n---\n\n## Related Pages\n\n" + relatedPages + "\n\n---\n\n*Auto-generated by sync-wiki.mjs - Last updated: " + today + "*\n";
}

function transformHome(sources) {
  const readme = stripBilingualNav(sources["README.md"]);
  const stats = extractStats();

  return addWikiHeader(
    "Evolith — Executable Architectural Governance Framework",
    `**Multi-Topology Reference Corpus** · **Spec-driven AI-DD** · **MIT License**`
  ) + `## What is Evolith?

Evolith Core is **not a documentation corpus**. It is an **executable governance framework** — a topology-agnostic, runtime-neutral technical standard that dictates **how** software is built, distributed through CLI, MCP, and REST interfaces, and enforced by verifiable rulesets.

**Progressive Architecture**: the framework's ability to scale systems by mutating between topologies according to the business lifecycle, preventing over-engineering and guaranteeing architectural coherence through automated execution.

---

## Vision

Evolith Core exists to become the definitive enterprise-grade operating system for software architecture governance: global, stack-agnostic, topology-aware, and executable by humans, delivery platforms, and AI agents.

---

## Supported Topologies

| Topology | Description |
|----------|-------------|
| **Modular Monolith** | Foundational topology for systems that start simple and mature without premature distribution |
| **Distributed Modules** | Services with explicit extraction readiness scoring |
| **Microservices** | Full decomposition with contract-first design |
| **Serverless** | Event-driven, auto-scaling, pay-per-execution on FaaS |
| **Event-Driven** | Async-first with message brokers, event sourcing, CQRS |
| **Data Mesh** | Domain-oriented, self-serve data platforms |
| **Edge Computing** | Distributed compute at the network edge |
| **Agentic / AI-First** | AI agents as first-class system actors with MCP |

---

## Three Interfaces

| Interface | Purpose |
|-----------|---------|
| **CLI** (\`@beyondnet/evolith-cli\`) | Validate code locally against rulesets |
| **MCP** (Model Context Protocol) | Inject architectural context into AI agents |
| **Core API** (REST) | Programmatic access for orchestration systems

---

## Quick Start

\`\`\`bash
npm install -g @beyondnet/evolith-cli
evolith-cli init
evolith-cli validate
evolith-mcp
\`\`\`

---

## Navigate by Role

| Role | Start Here |
|------|------------|
| **Architect** | [Architecture](https://github.com/beyondnetcode/evolith_arch32/wiki/Architecture) |
| **Developer** | [Getting Started](https://github.com/beyondnetcode/evolith_arch32/wiki/Getting-Started) |
| **QA / SRE** | [Governance](https://github.com/beyondnetcode/evolith_arch32/wiki/Governance) |
| **AI Agent** | [AGENTS.md](https://github.com/beyondnetcode/evolith_arch32/blob/main/AGENTS.md) |

---

## Repository Stats

- **${stats.totalGaps} tracked gaps** (${stats.doneGaps} done, ${stats.openGaps} open)
- **${countTopologyProfiles()} topology profiles** with full guidance corpus
- **${countMcpTools()} MCP tools** for AI agent integration
- **${countCiGates()} CI validation gates**
- **Bilingual** (English + Spanish) documentation
` + addWikiFooter("Home");
}

function transformGettingStarted(sources) {
  const cli = stripBilingualNav(sources["product/products/smart-cli/README.md"] || "");
  const mcp = stripBilingualNav(sources["product/products/mcp-services/README.md"] || "");

  return addWikiHeader(
    "Getting Started",
    "Install, configure, and validate your first satellite repository."
  ) + `## Prerequisites

- **Node.js** 20+ (LTS recommended)
- **npm** 9+ (comes with Node.js)
- **Git** 2.30+

---

## Installation

\`\`\`bash
npm install -g @beyondnet/evolith-cli
evolith-cli --version
# evolith-cli version 1.1.0
\`\`\`

---

## Quick Start

### 1. Initialize a Satellite Repository

\`\`\`bash
cd your-project
evolith-cli init
\`\`\`

Creates \`evolith.yaml\` with default F1 (Modular Monolith) configuration.

### 2. Run Validation

\`\`\`bash
evolith-cli validate
\`\`\`

### 3. Start MCP Server for AI Agents

\`\`\`bash
evolith-mcp
\`\`\`

---

## CLI Commands

| Command | Description |
|---------|-------------|
| \`evolith-cli init\` | Initialize satellite repository |
| \`evolith-cli validate\` | Validate against Evolith standards |
| \`evolith-cli validate --topology <name>\` | Validate against specific topology |
| \`evolith-cli adr create\` | Create Architecture Decision Record |
| \`evolith-cli adr list\` | List all ADRs |
| \`evolith-mcp\` | Start MCP server (stdio) |
| \`evolith-mcp --http\` | Start MCP server (HTTP) |

---

## MCP Integration

### Claude Desktop

\`\`\`json
{
  "mcpServers": {
    "evolith": {
      "command": "evolith-cli",
      "args": ["mcp", "serve"]
    }
  }
}
\`\`\`

### Available MCP Tools

| Tool | Description |
|------|-------------|
| \`evolith-validate\` | Validate repository |
| \`evolith-composable-validate\` | Composable validation (5 modes) |
| \`evolith-gate-evaluate\` | Evaluate SDLC phase gates |
| \`evolith-architecture-validate\` | Validate architecture topology |
| \`evolith-metrics\` | Get governance metrics |
` + addWikiFooter("Getting-Started");
}

function transformArchitecture(sources) {
  return addWikiHeader(
    "Architecture",
    "Topology profiles, ADRs, and architectural decisions."
  ) + `## Supported Topologies

Each topology is a fully isolated bounded context with its own ADRs, OPA policies, AI rulesets, and UMS contracts.

| Topology | Phase | Description |
|----------|-------|-------------|
| **Modular Monolith** | F1 | Starting point. Monolithic with strict module boundaries |
| **Distributed Modules** | F2 | Services with extraction readiness ≥ 70% |
| **Microservices** | F3 | Full decomposition with extraction readiness ≥ 80% |
| **Serverless** | Draft | FaaS and managed services |
| **Event-Driven** | Draft | Async-first with message brokers |
| **Data Mesh** | Draft | Domain-oriented data platforms |
| **Edge Computing** | Draft | Distributed compute at network edge |
| **Agentic / AI-First** | Draft | AI agents as first-class actors |

---

## Progressive Axis (F1 → F2 → F3)

\`\`\`
F1: Modular Monolith
  ↓ (extraction readiness ≥ 70%)
F2: Distributed Modules
  ↓ (extraction readiness ≥ 80%)
F3: Microservices
\`\`\`

Phase transitions require Architecture Board approval.

---

## Architecture Decision Records (ADRs)

ADRs capture significant architectural decisions. Each ADR includes:
- **Status**: Proposed → Accepted → Deprecated → Superseded
- **Context**: The problem or forces at play
- **Decision**: What was decided
- **Consequences**: What follows from the decision

Browse all ADRs: [reference/core/architecture/adrs/](https://github.com/beyondnetcode/evolith_arch32/tree/main/reference/core/architecture/adrs)

---

## Repository Structure

\`\`\`
reference/core/architecture/
  ├── adrs/                    # Architecture Decision Records
  │   ├── core/                # Core ADRs (ADR-0001 to ADR-0099)
  │   └── ai/                  # AI-specific ADRs
  ├── topologies/
  │   ├── progressive-axis/    # F1/F2/F3 topologies
  │   │   ├── modular-monolith/
  │   │   ├── distributed-modules/
  │   │   └── microservices/
  │   ├── serverless/
  │   ├── event-driven/
  │   ├── data-mesh/
  │   ├── edge-computing/
  │   └── agentic-ai/
  └── standards/               # Architecture standards
\`\`\`
` + addWikiFooter("Architecture");
}

function transformProducts(sources) {
  return addWikiHeader(
    "Products",
    "CLI, MCP Services, Core API, Agent Runtime — the four operational interfaces."
  ) + `## Product Overview

| Product | Package | Purpose |
|---------|---------|---------|
| **Evolith CLI** | \`@beyondnet/evolith-cli\` | Developer-facing governance tool |
| **MCP Services** | (bundled in CLI) | AI agent integration via MCP |
| **Core API** | \`src/apps/core-api\` | REST API for orchestration systems |
| **Agent Runtime** | \`src/packages/agent-runtime\` + \`src/apps/agent-runtime-api\` | Agentic mediation layer over Core |

---

## Evolith CLI

Command-line interface for governance, validation, and AI integration.

\`\`\`bash
npm install -g @beyondnet/evolith-cli
evolith-cli init
evolith-cli validate
evolith-mcp
\`\`\`

**Key commands**: init, validate, adr, standards, docs, mcp serve

Docs: [product/products/smart-cli/](https://github.com/beyondnetcode/evolith_arch32/tree/main/product/products/smart-cli)

---

## MCP Services

Exposes Evolith governance as real-time context for LLMs and autonomous agents through the Model Context Protocol.

| Capability | Count | Examples |
|---|:---:|---|
| **Tools** | 22 | evolith-validate, evolith-gate-evaluate |
| **Resources** | 7 | evolith://rulesets, evolith://phase-gates |
| **Prompts** | 7 | validate-repository, architecture-review |

**Transports**: stdio (JSON-RPC 2.0), Streamable HTTP

Docs: [product/products/mcp-services/](https://github.com/beyondnetcode/evolith_arch32/tree/main/product/products/mcp-services)

---

## Core API

Central validation, state, and governance engine. NestJS + TypeScript.

| Capability | Description |
|------------|-------------|
| **Gate Evaluation** | Validates quality gate criteria per SDLC phase |
| **Phase Transitioning** | Automates transitions based on evidence |
| **Architecture Verification** | Audits against multi-topology rulesets |
| **Drift Detection** | Tracks divergence from declared standards |

**Stack**: NestJS, TypeScript, PostgreSQL, MongoDB, Redis, OPA WASM

Docs: [product/products/core-api/](https://github.com/beyondnetcode/evolith_arch32/tree/main/product/products/core-api)

---

## Agent Runtime

Decoupled agentic layer that sits between external callers and Evolith Core. Implements a **Ports & Adapters (Hexagonal)** model — every dependency (Core evaluation, OPA, .harness, Tracker, Memory, Scheduler, Hermes) is hidden behind a port and satisfied by a swappable adapter.

\`\`\`
External Client / Tracker / Chat / CLI
        → Agent Runtime (POST /v1/agent/handle)
        → Ports  →  Adapters
        → .harness · Evolith Core · OPA · Tracker · Hermes
\`\`\`

| Capability | Description |
|------------|-------------|
| **Skill dispatch** | Routes intents to the correct governance tool via \`.harness\` |
| **Hermes integration** | Hermes Agent is one pluggable adapter — the runtime does not depend on it |
| **Policy validation** | OPA CLI adapter enforces governance policies per request |
| **Tracing** | HTTP Tracker adapter emits structured traces for every handled request |
| **Auth** | API key guard (Bearer / x-api-key), fail-closed in production |

**Key endpoints**: \`POST /v1/agent/handle\` · \`GET /v1/agent/skills\` · \`GET /health\`

**Package**: \`@beyondnet/evolith-agent-runtime\` · **Service**: \`src/apps/agent-runtime-api\` · **Deploy**: \`evolithruntime.beyondnet.cloud\`
` + addWikiFooter("Products");
}

function transformGovernance(sources) {
  const stats = extractStats();

  return addWikiHeader(
    "Governance",
    "SDLC phases, gap tracking, maturity scoring, and compliance."
  ) + `## Gap Tracking Board

| Metric | Value |
|--------|-------|
| **Total gaps** | ${stats.totalGaps} |
| **Done** | ${stats.doneGaps} |
| **Open** | ${stats.openGaps} |
| **In Progress** | 0 |
| **Deferred** | 0 |

Full board: [gap-tracking.md](https://github.com/beyondnetcode/evolith_arch32/blob/main/reference/core/control-center/gap-tracking.md)

---

## SDLC Phases

| Phase | Gate | Artifacts Required |
|-------|------|-------------------|
| **F1** Conceptualization | Inception Gate | Discovery Canvas, Technical Feasibility |
| **F2** Design | Design Gate | Ballpark Estimation, User Stories |
| **F3** Construction | Construction Gate | Test Suite, Coverage Report |
| **F4** Quality Assurance | QA Gate | Security Scan, Performance Report |
| **F5** Delivery | Release Gate | Release Notes, Rollback Plan |

---

## Winston Audit Waves

The Winston Audit is an automated architectural review that runs 3-5 expert lenses in parallel:

- **Wave III** (2026-06-23): GT-212 to GT-225 (14 gaps)
- **Wave IV** (2026-06-23): GT-226 to GT-248 (23 gaps from BMAD agent evolution)
- **Production-Readiness** (2026-06-25): GT-267 to GT-272
- **SDLC Deep Audit** (2026-06-25): GT-280 to GT-282

---

## Maturity Scoring

The intelligent data strength audit evaluates 9 workstreams (WS1-WS9):
- WS1: Rulesets
- WS2: SDLC Model
- WS3: OPA Engine
- WS4: Client Ingestion
- WS5: Three Interfaces
- WS6: Reporting
- WS7: Target Design
- WS8: Governance
- WS9: Extensibility

Current score: ~28% executable (MINIMAL_EXECUTABLE)

---

## CI Validation Gates

29 automated gates enforce governance:

| Gate | Script | Purpose |
|------|--------|---------|
| 01 | validate-docs | Markdown links, anchors, Mermaid |
| 03 | root-cleanliness | No unauthorized root items |
| 04 | bilingual-parity | EN/ES structure match |
| 05 | executive-summary | Summary freshness |
| 08 | validate-tracking | Gap closure evidence |
| 09 | reconcile-maturity | Maturity counters |
| 10 | contract-conformance | ADR-0073 envelope |
| 28 | native-evaluator-parity | OPA/Native parity |
` + addWikiFooter("Governance");
}

function transformContributing(sources) {
  const contributing = stripBilingualNav(sources["CONTRIBUTING.md"] || "");

  return addWikiHeader(
    "Contributing",
    "How to contribute to Evolith Core."
  ) + `## The BMAD Method

We use the **BMAD Method** (Specification-driven AI-Driven Development). You do not have to code alone — invoke our specialized AI agents:

- **Winston (Principal Architect)**: Architectural audits and gap tracking
- **Architect Agent**: Data Mesh contracts, Event-Driven patterns, ADRs
- **Developer Agent**: Secure patterns (OWASP), progressive architecture
- **QA Agent**: Contract testing, Rego policy validation
- **DevOps Agent**: Distributed deployments, GitHub Actions
- **Docs Agent**: Translation, markdown validations

---

## Golden Rules

### 1. Mandatory Bilingual Parity

Every documentation file must have English (\`.md\`) and Spanish (\`.es.md\`) versions with identical structure.

### 2. Architectural Agnosticism

Keep the reference agnostic unless editing a specific Authoritative Tech Stack Profile.

### 3. Validation Quality Gates

\`\`\`bash
# Validate Markdown links, anchors, Mermaid
node .harness/scripts/ci/01-validate-docs.mjs

# Verify bilingual structural parity
node .harness/scripts/ci/04-check-bilingual-parity.mjs
\`\`\`

---

## Pull Request Process

1. **Branching**: Follow ADR-0050 (gitflow). Prefix: \`feature/\`, \`docs/\`, \`fix/\`
2. **ADR Updates**: Architectural changes require ADR updates
3. **Commits**: Use [Conventional Commits](https://www.conventionalcommits.org/) (\`feat:\`, \`docs:\`, \`fix:\`)
4. **Review**: All PRs require review + automated CI validation

---

## Pre-commit Hook

The pre-commit hook presents 5 CI modes:

| Mode | What it runs |
|------|-------------|
| Skip | Nothing (~0s) |
| Fast | docs + tracking (~2s) |
| Governance | docs + tracking + maturity + contracts (~3s) |
| Auto | Detect changed files (~1-3s) |
| Full | All 29 CI scripts (~6-8s) |
` + addWikiFooter("Contributing");
}

function extractStats() {
  // The board moved under `gaps/`. Reading the old path returned "" and every
  // figure below silently fell back to a hardcoded 2025 snapshot -- and the
  // `312` baked into the regex meant the match could never succeed even once
  // the path was right, so the fallback was permanent by construction.
  const rel = "reference/core/control-center/gaps/gap-tracking.md";
  const tracking = readFileSafe(rel);
  if (!tracking) {
    throw new Error(
      `sync-wiki: cannot read the gap board at ${rel}.\n` +
      `Refusing to publish wiki stats from hardcoded fallbacks -- that is how ` +
      `"312 tracked gaps (290 done, 22 open)" survived on the public wiki long ` +
      `after the real board passed 500.`
    );
  }
  const progress = tracking.match(
    /\*\*Progress:\*\*\s*(\d+)\s*\/\s*(\d+)\s*done\s*·\s*(\d+)\s*in progress\s*·\s*(\d+)\s*pending\s*·\s*(\d+)\s*deferred/
  );
  if (!progress) {
    throw new Error(
      `sync-wiki: could not parse the Progress line in ${rel}. ` +
      `Fix the parser rather than shipping stale counts.`
    );
  }
  const [, done, total, inProgress, pending, deferred] = progress;
  return {
    totalGaps: Number(total),
    doneGaps: Number(done),
    openGaps: Number(inProgress) + Number(pending) + Number(deferred),
  };
}

/** Count topology profiles from the manifests, never from memory. */
function countTopologyProfiles() {
  const dir = path.join(root, "reference/core/architecture/topologies");
  if (!fs.existsSync(dir)) {
    throw new Error(`sync-wiki: topology directory not found at ${dir}`);
  }
  // Topologies live at the SECOND level: the first level is the category
  // (progressive-axis, execution, integration, data, ai) and the leaves are the
  // 8 actual profiles. Counting the first level yields 5 and is wrong.
  let n = 0;
  for (const cat of fs.readdirSync(dir, { withFileTypes: true })) {
    if (!cat.isDirectory()) continue;
    n += fs
      .readdirSync(path.join(dir, cat.name), { withFileTypes: true })
      .filter((e) => e.isDirectory()).length;
  }
  if (n === 0) throw new Error(`sync-wiki: scanned ${dir} and found zero topologies`);
  return n;
}

/** Count the numbered CI gate scripts, never from memory. */
function countCiGates() {
  const dir = path.join(root, ".harness/scripts/ci");
  if (!fs.existsSync(dir)) {
    throw new Error(`sync-wiki: CI script directory not found at ${dir}`);
  }
  const n = fs
    .readdirSync(dir)
    .filter((f) => /^\d+-.*\.mjs$/.test(f) && !f.endsWith(".test.mjs")).length;
  if (n === 0) throw new Error(`sync-wiki: scanned ${dir} and found zero CI gates`);
  return n;
}

/** Count the registered `evolith-*` MCP tools from source, never from memory. */
function countMcpTools() {
  const dir = path.join(root, "src/packages/mcp-server/src/tools");
  if (!fs.existsSync(dir)) {
    throw new Error(`sync-wiki: MCP tool directory not found at ${dir}`);
  }
  const names = new Set();
  for (const f of fs.readdirSync(dir)) {
    if (!f.endsWith(".ts") || f.endsWith(".spec.ts")) continue;
    const src = fs.readFileSync(path.join(dir, f), "utf8");
    for (const m of src.matchAll(/name:\s*['"](evolith-[a-z0-9-]+)['"]/g)) {
      names.add(m[1]);
    }
  }
  if (names.size === 0) {
    throw new Error(`sync-wiki: scanned ${dir} and found zero MCP tools`);
  }
  return names.size;
}

// ─── Fingerprint & Diff Detection ──────────────────────────────────────────────

function computeFingerprint() {
  const sources = [];
  for (const page of Object.values(WIKI_SOURCES)) {
    for (const f of page.files) {
      const content = readFileSafe(f);
      sources.push(content);
    }
  }
  return createHash("sha256").update(sources.join("\n---\n")).digest("hex");
}

function isWikiStale() {
  if (!fs.existsSync(fingerprintFile)) return true;
  const stored = fs.readFileSync(fingerprintFile, "utf-8").trim();
  return stored !== computeFingerprint();
}

function saveFingerprint() {
  fs.mkdirSync(wikiDir, { recursive: true });
  fs.writeFileSync(fingerprintFile, computeFingerprint());
}

// ─── Main ──────────────────────────────────────────────────────────────────────

function main() {
  const args = process.argv.slice(2);
  const force = args.includes("--force");
  const allowContentLoss = args.includes("--allow-content-loss");
  const check = args.includes("--check");

  if (check) {
    if (isWikiStale()) {
      console.log("⚠️  Wiki is stale — documentation has changed since last sync.");
      process.exit(1);
    }
    console.log("✅ Wiki is up to date.");
    process.exit(0);
  }

  if (!force && !isWikiStale()) {
    console.log("✅ Wiki is already up to date. Use --force to regenerate.");
    process.exit(0);
  }

  console.log("📝 Generating Wiki pages...");

  fs.mkdirSync(wikiDir, { recursive: true });

  let generated = 0;
  let skipped = 0;
  for (const [pageName, config] of Object.entries(WIKI_SOURCES)) {
    const sources = {};
    for (const f of config.files) {
      sources[f] = readFileSafe(f);
    }
    const content = config.transform(sources);
    const outPath = path.join(wikiDir, pageName);

    // Content-loss guard.
    //
    // `reference/wiki/` claims to be auto-generated, but pages here carry
    // hand-written sections the templates below cannot reproduce (the Agent
    // Runtime section in Products, the topology table in Architecture). Until
    // this run, that content survived only because the generator was writing to
    // a phantom `wiki/` directory at the repo root -- the bug was the only thing
    // protecting it. With the path repaired, `--force` (which .husky/pre-push
    // invokes on every doc change) would silently overwrite those sections.
    //
    // So: refuse to shrink a page. Fold the missing content into the template
    // above, or pass --allow-content-loss if the removal is genuinely intended.
    if (!allowContentLoss && fs.existsSync(outPath)) {
      // Line-level, not heading-level: the content at risk includes table rows
      // INSIDE an existing section (the topology table in Architecture), which a
      // heading-only comparison walks straight past.
      const boilerplate = /^\s*$|Last updated:|^---$/;
      const existing = fs.readFileSync(outPath, "utf8");
      const newLines = new Set(content.split("\n").map((l) => l.trim()));
      const dropped = existing
        .split("\n")
        .map((l) => l.trim())
        .filter((l) => !boilerplate.test(l) && !newLines.has(l));
      if (dropped.length) {
        // Skip the page rather than throwing: this runs in .husky/pre-push, and
        // blocking every push would be a worse failure than an out-of-date page.
        // The content is preserved and the reason is stated loudly.
        console.warn(
          `  ⏭  ${pageName} SKIPPED — regenerating it would drop ${dropped.length} ` +
          `hand-written line(s) the template cannot reproduce:\n` +
          dropped.map((h) => `       ${h}`).join("\n") + "\n" +
          `       Port them into the template in this script, then this page ` +
          `will regenerate normally (or pass --allow-content-loss).`
        );
        skipped++;
        continue;
      }
    }

    fs.writeFileSync(outPath, content);
    generated++;
    console.log(`  ✅ ${pageName}`);
  }

  saveFingerprint();
  console.log(`\n📦 Generated ${generated} wiki page(s) in reference/wiki/${skipped ? `, ${skipped} skipped to avoid content loss` : ""}`);
  console.log("   Run 'git add reference/wiki/' to include in commit.");
}

main();
