import * as path from 'node:path';
import type { IFileSystem } from '@beyondnet/evolith-core';
import { McpTool } from '../mcp/tool.interface';

/**
 * `evolith-fixtures` — seed reproducible fixtures and sample data for demos and
 * tests. Mirrors the `evolith fixtures [type]` CLI command.
 *
 * The fixture *content* is generated by the same deterministic templates the CLI
 * command uses (there is no shared core-domain fixture service — the CLI defines
 * these inline). Files are written through the shared `IFileSystem` port from
 * `@beyondnet/evolith-core-domain`, i.e. the exact same adapter the CLI injects
 * via `@Inject('IFileSystem')`, so behaviour stays in lock-step across surfaces.
 *
 * Writes files → declared `mutative` / `scope: 'write'`. The dispatch therefore
 * requires `{ apply: true, approvalToken }` before execution.
 */

type FixtureType = 'demo' | 'adr' | 'ruleset' | 'evolith' | 'full';

interface FixtureFile {
  relativePath: string;
  content: string;
}

const VALID_TYPES: readonly FixtureType[] = ['demo', 'adr', 'ruleset', 'evolith', 'full'];

function generateEvolithFixtures(): FixtureFile[] {
  return [
    {
      relativePath: 'evolith.yaml',
      content: [
        'coreRef:',
        '  version: "1.0.0"',
        '  path: "../evolith"',
        'governance:',
        '  version: "1.0"',
        'product:',
        '  name: "demo-project"',
        '  type: "library"',
        'phases:',
        '  - "phase-0"',
        '  - "phase-1"',
        '  - "phase-2"',
        '',
      ].join('\n'),
    },
  ];
}

function generateAdrFixtures(): FixtureFile[] {
  return [
    {
      relativePath: 'docs/adr/0001-record-architecture-decisions.md',
      content: [
        '# ADR-0001: Record Architecture Decisions',
        '',
        '**Status:** Accepted',
        '**Date:** 2026-06-01',
        '',
        '## Context',
        '',
        'We need to record the architectural decisions made on this project.',
        '',
        '## Decision',
        '',
        'We will use Architecture Decision Records (ADRs) as described by Michael Nygard.',
        '',
        '## Consequences',
        '',
        '- ADRs are stored in `docs/adr/`',
        '- Each ADR follows the standard template',
        '',
      ].join('\n'),
    },
    {
      relativePath: 'docs/adr/0002-use-clean-architecture.md',
      content: [
        '# ADR-0002: Use Clean Architecture',
        '',
        '**Status:** Accepted',
        '**Date:** 2026-06-01',
        '',
        '## Context',
        '',
        'The application needs a clear separation of concerns to remain maintainable as it grows.',
        '',
        '## Decision',
        '',
        'We will adopt Clean Architecture with domain, application, infrastructure, and presentation layers.',
        '',
        '## Consequences',
        '',
        '- Domain layer has zero external dependencies',
        '- Use cases encapsulate business rules',
        '- Infrastructure depends on abstractions, not concretions',
        '',
      ].join('\n'),
    },
    {
      relativePath: 'docs/adr/0003-use-nestjs-for-backend.md',
      content: [
        '# ADR-0003: Use NestJS for Backend',
        '',
        '**Status:** Accepted',
        '**Date:** 2026-06-01',
        '',
        '## Context',
        '',
        'The backend requires a structured framework with built-in DI, modularity, and testing support.',
        '',
        '## Decision',
        '',
        'We will use NestJS with TypeScript for the backend services.',
        '',
        '## Consequences',
        '',
        '- Dependency injection is built-in via NestJS DI',
        '- Modules provide clear boundaries',
        '- Testing utilities are available out of the box',
        '',
      ].join('\n'),
    },
  ];
}

function generateRulesetFixtures(): FixtureFile[] {
  return [
    {
      relativePath: 'rulesets/architecture.yaml',
      content: [
        'ruleset:',
        '  id: "architecture-conventions"',
        '  version: "1.0"',
        '  rules:',
        '    - id: "F1"',
        '      title: "Domain layer isolation"',
        '      description: "Domain layer must not depend on infrastructure"',
        '      severity: "error"',
        '    - id: "F2"',
        '      title: "Use case naming"',
        '      description: "Use cases must follow <Verb><Noun>UseCase pattern"',
        '      severity: "warning"',
        '',
      ].join('\n'),
    },
    {
      relativePath: 'rulesets/naming.yaml',
      content: [
        'ruleset:',
        '  id: "naming-conventions"',
        '  version: "1.0"',
        '  rules:',
        '    - id: "N1"',
        '      title: "File naming"',
        '      description: "Files must use kebab-case"',
        '      severity: "error"',
        '    - id: "N2"',
        '      title: "Class naming"',
        '      description: "Classes must use PascalCase"',
        '      severity: "error"',
        '',
      ].join('\n'),
    },
  ];
}

function generateFixtures(type: FixtureType): FixtureFile[] {
  switch (type) {
    case 'evolith':
      return generateEvolithFixtures();
    case 'adr':
      return generateAdrFixtures();
    case 'ruleset':
      return generateRulesetFixtures();
    case 'demo':
      return [...generateEvolithFixtures(), ...generateAdrFixtures()];
    case 'full':
      return [...generateEvolithFixtures(), ...generateAdrFixtures(), ...generateRulesetFixtures()];
  }
}

/** Fixture seeding tool (single operation, mirrors `evolith fixtures [type]`). */
export function createFixturesTools(fs: IFileSystem): McpTool[] {
  return [
    {
      mutative: true,
      scope: 'write' as const,
      schema: {
        name: 'evolith-fixtures',
        description:
          'Seed reproducible fixtures and sample data (evolith.yaml, ADRs, rulesets) for demos and tests. Mirrors the "evolith fixtures" CLI command.',
        inputSchema: {
          type: 'object',
          properties: {
            type: {
              type: 'string',
              description: 'Fixture type to generate: demo, adr, ruleset, evolith, full',
              enum: ['demo', 'adr', 'ruleset', 'evolith', 'full'],
              default: 'demo',
            },
            dir: {
              type: 'string',
              description: 'Target directory for fixtures (defaults to the current working directory)',
            },
            dryRun: {
              type: 'boolean',
              description: 'Preview the files that would be written without touching the filesystem',
              default: false,
            },
          },
          required: [],
        },
      },
      execute: async (args: Record<string, unknown>): Promise<unknown> => {
        const fixtureType = ((args.type as string) || 'demo') as FixtureType;
        const targetDir = (args.dir as string) || process.cwd();
        const dryRun = Boolean(args.dryRun);

        if (!VALID_TYPES.includes(fixtureType)) {
          throw new Error(
            `Invalid fixture type: ${fixtureType}. Valid types: ${VALID_TYPES.join(', ')}`,
          );
        }

        const files = generateFixtures(fixtureType);

        if (dryRun) {
          // Return the raw payload only — the dispatch wraps it in the canonical
          // ADR-0073 output envelope { success, data, meta }.
          return {
            type: fixtureType,
            targetDir,
            dryRun: true,
            created: files.map((f) => f.relativePath),
          };
        }

        const created: string[] = [];
        const errors: Array<{ file: string; message: string }> = [];

        for (const file of files) {
          try {
            const fullPath = path.join(targetDir, file.relativePath);
            await fs.ensureDir(path.dirname(fullPath));
            await fs.writeFile(fullPath, file.content);
            created.push(file.relativePath);
          } catch (err) {
            const message = err instanceof Error ? err.message : String(err);
            errors.push({ file: file.relativePath, message });
          }
        }

        if (errors.length > 0) {
          // Surface IO failures as a thrown error so the dispatch maps it to the
          // ADR-0073 error envelope (mirrors the CLI's IO_ERROR exit path).
          const detail = errors.map((e) => `${e.file}: ${e.message}`).join('; ');
          throw new Error(
            `Failed to write ${errors.length} of ${files.length} fixture file(s): ${detail}`,
          );
        }

        return {
          type: fixtureType,
          targetDir,
          dryRun: false,
          created,
        };
      },
    },
  ];
}
