import { getAutoFixTools } from '../src/infrastructure/mcp/tools/auto-fix';
import { NodeFileSystemProvider } from '../src/infrastructure/providers/node-filesystem.provider';
import { YamlConfigParserProvider } from '../src/infrastructure/providers/config-parser.provider';
import { IFileSystem, IConfigParser } from '@evolith/core-domain/domain/interfaces';
import * as path from 'path';
import * as fs from 'fs/promises';

describe('Auto-Fix E2E', () => {
  let tempDir: string;
  let testFs: IFileSystem;
  let testConfigParser: IConfigParser;

  beforeEach(async () => {
    tempDir = path.join(process.cwd(), 'test-temp-auto-fix-' + Date.now());
    await fs.mkdir(tempDir, { recursive: true });
    
    const fsProvider = new NodeFileSystemProvider();
    testFs = fsProvider.createFileSystem();
    
    const configProvider = new YamlConfigParserProvider();
    testConfigParser = configProvider.createConfigParser('yaml');
  });

  afterEach(async () => {
    try {
      await fs.rm(tempDir, { recursive: true, force: true });
    } catch {
      // Ignore cleanup errors
    }
  });

  describe('Real auto-fix scenarios', () => {
    it('should preview domain purity fixes without applying', async () => {
      const testFile = path.join(tempDir, 'domain-service.ts');
      await fs.writeFile(testFile, 'import { Injectable } from "@nestjs/common";\nexport class UserService {}');

      const tools = getAutoFixTools(testFs, testConfigParser);
      const tool = tools[0];

      const result = await tool.execute({
        rulesetId: 'domain-purity',
        violations: [
          {
            ruleId: 'domain-must-be-pure',
            filePath: testFile,
            message: 'Domain layer imports framework',
          },
        ],
        dryRun: true,
      });

      expect(result.fixesApplied).toBe(0);
      expect(result.fixesPreview).toBeDefined();
      
      const contentAfter = await fs.readFile(testFile, 'utf-8');
      expect(contentAfter).toContain('@nestjs/common');
    });

    it('should apply missing domain interface generation', async () => {
      const testFile = path.join(tempDir, 'IPort.ts');

      const tools = getAutoFixTools(testFs, testConfigParser);
      const tool = tools[0];

      await tool.execute({
        rulesetId: 'hexagonal-boundaries',
        violations: [
          {
            ruleId: 'missing-domain-interface',
            filePath: testFile,
            message: 'Port interface missing',
            suggestedFix: 'interface IGeneratedPort',
          },
        ],
        dryRun: false,
      });

      const contentAfter = await fs.readFile(testFile, 'utf-8');
      expect(contentAfter).toContain('IGeneratedPort');
      expect(contentAfter).toContain('Auto-generated by evolith-auto-fix');
    });

    it('should handle multiple violation types in single run', async () => {
      const file1 = path.join(tempDir, 'service.ts');
      const file2 = path.join(tempDir, 'usecase.ts');
      const file3 = path.join(tempDir, 'IPort.ts');

      await fs.writeFile(file1, 'import { Module } from "@nestjs/common";');
      await fs.writeFile(file2, 'import { Logger } from "@nestjs/common";');

      const tools = getAutoFixTools(testFs, testConfigParser);
      const tool = tools[0];

      const result = await tool.execute({
        rulesetId: 'comprehensive',
        violations: [
          { ruleId: 'domain-must-be-pure', filePath: file1, message: 'Framework import' },
          { ruleId: 'hexagonal-boundaries', filePath: file2, message: 'Boundary violation' },
          { ruleId: 'missing-domain-interface', filePath: file3, message: 'Missing port' },
        ],
        dryRun: true,
      });

      expect(result.totalViolations).toBe(3);
      expect(result.summary).toBeDefined();
    });

    it('should report failed fixes gracefully', async () => {
      const tools = getAutoFixTools(testFs, testConfigParser);
      const tool = tools[0];

      const result = await tool.execute({
        rulesetId: 'test',
        violations: [
          {
            ruleId: 'domain-must-be-pure',
            filePath: '/nonexistent/path/file.ts',
            message: 'File does not exist',
          },
        ],
        dryRun: false,
      });

      expect(result.fixesApplied).toBe(0);
      expect(result.summary).toContain('Failed:');
    });

    it('should respect dir parameter for relative paths', async () => {
      const subdir = path.join(tempDir, 'subdir');
      await fs.mkdir(subdir, { recursive: true });
      
      const testFile = path.join(subdir, 'IPort.ts');

      const tools = getAutoFixTools(testFs, testConfigParser);
      const tool = tools[0];

      await tool.execute({
        rulesetId: 'hexagonal',
        violations: [
          {
            ruleId: 'missing-domain-interface',
            filePath: 'subdir/IPort.ts',
            message: 'Missing port',
          },
        ],
        dir: tempDir,
        dryRun: false,
      });

      const exists = await fs.access(testFile).then(() => true).catch(() => false);
      expect(exists).toBe(true);
    });
  });

  describe('Auto-fix summary generation', () => {
    it('should provide accurate counts in summary', async () => {
      const tools = getAutoFixTools(testFs, testConfigParser);
      const tool = tools[0];

      const result = await tool.execute({
        rulesetId: 'test',
        violations: [
          { ruleId: 'missing-domain-interface', filePath: 'a.ts', message: 'test' },
          { ruleId: 'missing-domain-interface', filePath: 'b.ts', message: 'test' },
          { ruleId: 'unknown-type', filePath: 'c.ts', message: 'test' },
        ],
        dryRun: true,
      });

      expect(result.summary).toMatch(/Applied:\s*\d+/);
      expect(result.summary).toMatch(/Preview:\s*\d+/);
      expect(result.summary).toMatch(/Manual Review:\s*\d+/);
    });
  });
});
