apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: cpu-stress
  namespace: evolith
spec:
  mode: all
  selector:
    namespaces:
      - evolith
    labelSelectors:
      app: core-api
  stressors:
    cpu:
      workers: 2
      load: 80
  duration: "180s"
