apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-partition
  namespace: evolith
spec:
  action: partition
  mode: all
  selector:
    namespaces:
      - evolith
    labelSelectors:
      app: core-api
  direction: both
  target:
    selector:
      namespaces:
        - evolith
      labelSelectors:
        app: mcp-server
    mode: all
  duration: "300s"
