jest.mock('chalk', () => {
  const identity = (str: string) => str;
  return new Proxy(identity, {
    get: (_target, prop) => (prop === '__esModule' ? false : identity),
  });
});

import * as fs from 'node:fs';
import * as path from 'node:path';
import { tmpdir } from 'node:os';
import { PhaseArtifactsCommand } from './phase-artifacts.command';
import { NodeFileSystemProvider } from '../../infrastructure/providers/node-filesystem.provider';
import type { ILogger } from '@beyondnet/evolith-core-domain/domain/interfaces';
import type { PhaseArtifactResult } from '@beyondnet/evolith-core-domain/application/services';

/**
 * GT-562 — `topology phase-artifacts` had ZERO coverage. It is advisory, but a
 * gate consumes its verdict, so the branches that decide WHAT IT REPORTS matter:
 *
 *   - an invalid `--phase` must be REFUSED, not quietly measured as something
 *     else (a bogus phase silently scoring 100/100 is the failure mode this
 *     codebase keeps producing);
 *   - a failure in JSON mode must produce an error envelope AND a non-zero exit
 *     code, never a success envelope with empty contents;
 *   - the human and JSON surfaces must agree on the same result.
 *
 * ## Why this spec builds its own corpus instead of using the bundled one
 *
 * The first version of this spec ran against the REAL bundled corpus at
 * `src/sdk/cli/rulesets/`, on the reasoning that "a test passing here means the
 * shipped corpus is actually readable". Two things were wrong with that.
 *
 * 1. It made a UNIT TEST depend on a BUILD ARTIFACT. That directory is
 *    gitignored (`rulesets/*`, minus `rulesets/agents/`) and is generated by
 *    `scripts/copy-rulesets.js` on the CLI's `prebuild`. CI runs `npm ci` at the
 *    workspace root, which never triggers that prebuild, so in CI the corpus is
 *    absent, `resolveRulesets()` correctly throws, the command emits an ERROR
 *    envelope, and all nine tests died on `envelope.data.phase` with
 *    `TypeError: Cannot read properties of undefined`. It passed locally only
 *    because a developer tree carries a bundled copy from an earlier build. A
 *    test that silently requires a build step is environment-dependent by
 *    construction.
 *
 * 2. The dependency bought nothing AT THE TIME, and the reason it bought nothing
 *    was itself a defect rather than a property of the corpus.
 *
 *    CORRECTED: an earlier version of this comment asserted that "NO topology in
 *    the real corpus defines `phaseProfiles` at all (verified across all five:
 *    data-mesh, serverless, agentic-ai, edge-computing, event-driven)". That was
 *    false, and those five are exactly the five that were being SHADOWED.
 *    `TopologyCatalogService` aggregates several roots and de-duplicates by
 *    `metadata.id` on first occurrence; `src/rulesets/topologies` is probed
 *    before `reference/core/architecture/topologies`, and only the reference
 *    copies carried `designProfile`/`phaseProfiles`. So the verification was
 *    performed through the shadow and recorded its result as a fact about the
 *    corpus. All eight topologies now resolve with a `designProfile`, and seven
 *    of eight with `phaseProfiles` (modular-monolith genuinely has none — that
 *    is a content gap, not a shadow).
 *
 *    The catalogue now throws when a shadowed manifest is richer than the
 *    winning one, so this class of silent loss cannot recur.
 *
 * The fixture below is therefore both hermetic AND strictly stronger: it defines
 * a topology that really does contribute required, conditional and
 * unconditional-conditional artifacts, so the union logic is actually measured.
 *
 * The bundled-resolution path itself — `resolveRulesets()` with no `--core` —
 * is covered by `infrastructure/paths/rulesets-resolver.bundled.spec.ts`, which
 * is where that concern belongs.
 */

const silentLogger: ILogger = {
  log: () => undefined,
  info: () => undefined,
  warn: () => undefined,
  error: () => undefined,
  debug: () => undefined,
} as unknown as ILogger;

/** Artifacts the fixture topology contributes on top of the universal profile. */
const FIXTURE_TOPOLOGY = 'fixture-topology';
const FIXTURE_REQUIRED = 'fixture-required-report';
const FIXTURE_CONDITIONAL = 'fixture-conditional-report';
const FIXTURE_UNCONDITIONAL = 'fixture-unconditional-report';

describe('PhaseArtifactsCommand', () => {
  let command: PhaseArtifactsCommand;
  let logSpy: jest.SpyInstance;
  let originalExitCode: typeof process.exitCode;
  let corpusRoot: string;

  function stdout(): string {
    return logSpy.mock.calls.map((c) => String(c[0])).join('\n');
  }

  /**
   * Parse stdout as an ADR-0073 envelope and return its `data`.
   *
   * Reads the envelope rather than reaching straight for `.data` so that a
   * command failure reports WHAT FAILED. The predecessor of this helper was
   * `JSON.parse(stdout()).data`, and when the corpus went missing in CI every
   * assertion failed with `Cannot read properties of undefined (reading
   * 'phase')` — which names the assertion, not the cause, and cost a CI cycle to
   * diagnose. An error envelope must surface its own message.
   */
  function successData(): PhaseArtifactResult {
    const raw = stdout();
    if (!raw.trim()) {
      throw new Error('The command produced no stdout at all; expected a JSON envelope.');
    }
    let envelope: { success?: boolean; data?: unknown; error?: { code?: string; message?: string } };
    try {
      envelope = JSON.parse(raw);
    } catch {
      throw new Error(`Expected a JSON envelope on stdout, got:\n${raw.slice(0, 2000)}`);
    }
    if (envelope.data === undefined) {
      throw new Error(
        'Expected a SUCCESS envelope but the command emitted an error envelope: ' +
          `[${envelope.error?.code ?? 'no code'}] ${envelope.error?.message ?? '(no message)'}`,
      );
    }
    return envelope.data as PhaseArtifactResult;
  }

  beforeAll(() => {
    // A minimal but genuine corpus: `rulesets/topologies` is what qualifies the
    // directory as a corpus root (`RULESETS_CORPUS_MARKERS`), and the manifest is
    // read by the real TopologyCatalogService through the real filesystem
    // provider — nothing here is stubbed, it is simply OURS rather than a build
    // artifact that may or may not exist.
    corpusRoot = fs.mkdtempSync(path.join(tmpdir(), 'evolith-phase-artifacts-'));
    const topologyDir = path.join(corpusRoot, 'rulesets', 'topologies', FIXTURE_TOPOLOGY);
    fs.mkdirSync(topologyDir, { recursive: true });
    fs.writeFileSync(
      path.join(topologyDir, 'topology.manifest.json'),
      JSON.stringify(
        {
          // Must match what TopologyCatalogService.readManifest accepts, exactly
          // as the shipped manifests do — the fixture is validated by the real
          // reader, not waved through.
          apiVersion: 'evolith.dev/topology/v1',
          kind: 'TopologyManifest',
          metadata: {
            id: FIXTURE_TOPOLOGY,
            name: 'Fixture Topology',
            dimension: 'integration',
            status: 'accepted',
            version: '1.0.0',
          },
          spec: {
            summary: 'Test-only topology that contributes downstream phase artifacts.',
            topologyType: 'integration',
            phaseProfiles: {
              quality: {
                required: [{ artifactKind: FIXTURE_REQUIRED }],
                conditional: [
                  // A `condition` keeps it truly conditional (informational)…
                  { artifactKind: FIXTURE_CONDITIONAL, condition: 'when the topology is public-facing' },
                  // …while a conditional entry WITHOUT one is required outright.
                  { artifactKind: FIXTURE_UNCONDITIONAL },
                ],
              },
            },
          },
        },
        null,
        2,
      ),
    );
  });

  afterAll(() => {
    fs.rmSync(corpusRoot, { recursive: true, force: true });
  });

  beforeEach(() => {
    command = new PhaseArtifactsCommand(new NodeFileSystemProvider(), silentLogger);
    logSpy = jest.spyOn(console, 'log').mockImplementation(() => undefined);
    originalExitCode = process.exitCode;
    process.exitCode = undefined;
  });

  afterEach(() => {
    process.exitCode = originalExitCode;
    jest.restoreAllMocks();
  });

  describe('phase validation', () => {
    it.each([undefined, '', 'design', 'discovery', 'CONSTRUCTION'])(
      'refuses to measure anything for the invalid phase %p',
      async (phase) => {
        await expect(
          command.executeCommand([], {
            phase: phase as never,
            core: corpusRoot,
            topologies: [],
            declared: [],
          }),
        ).rejects.toThrow('--phase must be one of: construction, quality, deployment');
      },
    );

    it('reports an invalid phase as an INVALID_PHASE envelope with exit code 1 in JSON mode', async () => {
      // JSON mode must not throw — but it must not look successful either.
      await command.executeCommand([], { phase: 'nope' as never, core: corpusRoot, format: 'json' });

      const envelope = JSON.parse(stdout());
      expect(envelope.error.code).toBe('INVALID_PHASE');
      expect(envelope.success).not.toBe(true);
      expect(process.exitCode).toBe(1);
    });

    it.each(['construction', 'quality', 'deployment'] as const)('accepts the downstream phase %s', async (phase) => {
      await command.executeCommand([], { phase, core: corpusRoot, topologies: [], declared: [], format: 'json' });

      expect(successData().phase).toBe(phase);
      expect(process.exitCode).toBeUndefined();
    });
  });

  describe('measurement', () => {
    it('reports artifacts declared as present and the remainder as missing', async () => {
      await command.executeCommand([], {
        phase: 'quality',
        core: corpusRoot,
        topologies: [],
        declared: [],
        format: 'json',
      });
      const baseline = successData();
      // The universal profile must actually require something, or this command
      // would score everything 100/100 and mean nothing.
      expect(baseline.missingArtifacts.length).toBeGreaterThan(0);
      const firstRequired = baseline.missingArtifacts[0];
      logSpy.mockClear();

      await command.executeCommand([], {
        phase: 'quality',
        core: corpusRoot,
        topologies: [],
        declared: [firstRequired],
        format: 'json',
      });

      const result = successData();
      expect(result.presentArtifacts).toContain(firstRequired);
      expect(result.missingArtifacts).not.toContain(firstRequired);
      expect(result.completeness).toBeGreaterThan(baseline.completeness);
    });

    it('scores 100 only when every required artifact is declared', async () => {
      await command.executeCommand([], {
        phase: 'deployment',
        core: corpusRoot,
        topologies: [],
        declared: [],
        format: 'json',
      });
      const required = successData().missingArtifacts;
      logSpy.mockClear();

      await command.executeCommand([], {
        phase: 'deployment',
        core: corpusRoot,
        topologies: [],
        declared: [...required],
        format: 'json',
      });

      const result = successData();
      expect(result.missingArtifacts).toEqual([]);
      expect(result.completeness).toBe(100);
    });

    it('adds the phase-profile artifacts of a confirmed topology to the universal requirement set', async () => {
      // The union branch the real corpus cannot exercise: no shipped topology
      // declares `spec.phaseProfiles`, so without this fixture the topology arm
      // of `PhaseArtifactProfileService.evaluate` is dead weight in every test.
      await command.executeCommand([], {
        phase: 'quality',
        core: corpusRoot,
        topologies: [FIXTURE_TOPOLOGY],
        declared: [],
        format: 'json',
      });

      const result = successData();
      expect(result.requiredArtifacts).toContain(FIXTURE_REQUIRED);
      // A conditional entry with NO `condition` is required outright…
      expect(result.requiredArtifacts).toContain(FIXTURE_UNCONDITIONAL);
      // …one WITH a condition stays informational and out of the score.
      expect(result.conditionalArtifacts).toContain(FIXTURE_CONDITIONAL);
      expect(result.requiredArtifacts).not.toContain(FIXTURE_CONDITIONAL);
    });

    it('leaves other phases untouched by a topology profile that only covers quality', async () => {
      // `phaseProfiles.construction` is absent on the fixture, so the optional
      // index must degrade to the universal profile rather than leaking the
      // quality profile into construction.
      await command.executeCommand([], {
        phase: 'construction',
        core: corpusRoot,
        topologies: [FIXTURE_TOPOLOGY],
        declared: [],
        format: 'json',
      });

      const result = successData();
      expect(result.requiredArtifacts).not.toContain(FIXTURE_REQUIRED);
    });

    it('treats an unknown topology as contributing no extra requirements rather than failing', async () => {
      // `catalog.get` returns undefined for an id that is not in the corpus; the
      // optional-chain fallback must degrade to the universal profile only.
      await command.executeCommand([], {
        phase: 'construction',
        core: corpusRoot,
        topologies: ['no-such-topology'],
        declared: [],
        format: 'json',
      });

      const withUnknown = successData();
      logSpy.mockClear();
      await command.executeCommand([], {
        phase: 'construction',
        core: corpusRoot,
        topologies: [],
        declared: [],
        format: 'json',
      });
      const baseline = successData();

      expect([...withUnknown.missingArtifacts].sort()).toEqual([...baseline.missingArtifacts].sort());
    });

    it('defaults topologies and declared to empty when the flags are omitted entirely', async () => {
      await command.executeCommand([], { phase: 'quality', core: corpusRoot, format: 'json' });

      const result = successData();
      expect(result.presentArtifacts).toEqual([]);
      expect(result.phase).toBe('quality');
    });
  });

  describe('failure handling', () => {
    it('emits an INTERNAL_ERROR envelope and exit code 1 when the corpus cannot be resolved (JSON)', async () => {
      await command.executeCommand([], {
        phase: 'quality',
        core: '/definitely/not/a/core/checkout',
        format: 'json',
      });

      const envelope = JSON.parse(stdout());
      expect(envelope.error.code).toBe('INTERNAL_ERROR');
      expect(envelope.error.message).toContain('/definitely/not/a/core/checkout');
      expect(process.exitCode).toBe(1);
    });

    it('re-throws in human mode so the base command renders the failure', async () => {
      await expect(
        command.executeCommand([], { phase: 'quality', core: '/definitely/not/a/core/checkout' }),
      ).rejects.toThrow();
    });
  });

  describe('human output', () => {
    it('prints the completeness score and both artifact lists', async () => {
      await command.executeCommand([], { phase: 'quality', core: corpusRoot, topologies: [], declared: [] });

      const out = stdout();
      expect(out).toContain('Phase-Artifact Completeness');
      expect(out).toContain('Completeness:');
      expect(out).toContain('Present:');
      expect(out).toContain('Missing:');
    });

    it('prints the conditional section only when a topology contributes one', async () => {
      await command.executeCommand([], {
        phase: 'quality',
        core: corpusRoot,
        topologies: [FIXTURE_TOPOLOGY],
        declared: [],
      });

      expect(stdout()).toContain('Conditional (informational)');
      expect(stdout()).toContain(FIXTURE_CONDITIONAL);
    });

    it('states that the result is advisory, so it is not read as a gate verdict', async () => {
      await command.executeCommand([], { phase: 'quality', core: corpusRoot, topologies: [], declared: [] });

      expect(stdout()).toContain('advisory & non-binding');
    });
  });

  describe('option parsers', () => {
    it('parseTopologies splits a comma list and drops blank entries', () => {
      expect(command['parseTopologies']('microservices, event-driven,,')).toEqual([
        'microservices',
        'event-driven',
      ]);
    });

    it('parseDeclared splits a comma list and trims each entry', () => {
      expect(command['parseDeclared'](' test-summary-report , coverage-report ')).toEqual([
        'test-summary-report',
        'coverage-report',
      ]);
    });

    it.each([
      ['parseCore', '/some/core'],
      ['parsePhase', 'quality'],
      ['parseFormat', 'json'],
    ])('%s returns the value as-is', (method, value) => {
      expect((command as unknown as Record<string, (v: string) => unknown>)[method](value)).toBe(value);
    });
  });
});
