// AUTO-GENERATED by scripts/gen-api-catalog.mjs from the live @beyondnet/evolith-mcp
// server (tools/list + resources/list). Do NOT edit by hand — run
// `npm run gen:api-catalog` to refresh. Source of truth: the MCP server (GT-460).

import { ApiEntry, ApiResource } from './api.catalog';

export const GENERATED_TOOLS: ApiEntry[] = [
  {
    "name": "evolith-agent-install",
    "description": "Install a new Evolith agent"
  },
  {
    "name": "evolith-agent-list",
    "description": "List all installed Evolith agents"
  },
  {
    "name": "evolith-agent-remove",
    "description": "Remove an Evolith agent"
  },
  {
    "name": "evolith-agent-run",
    "description": "Run an intent through the Agent Runtime pipeline"
  },
  {
    "name": "evolith-agent-upgrade",
    "description": "Upgrade an existing Evolith agent"
  },
  {
    "name": "evolith-agent-validate",
    "description": "Validate a specific agent ruleset"
  },
  {
    "name": "evolith-architecture-validate",
    "description": "Validate repository architecture along the progressive maturity axis (modular-monolith → distributed-modules → microservices). Use deep=true for import graph analysis, layer violations, and coupling metrics."
  },
  {
    "name": "evolith-auto-fix",
    "description": "Apply automatic fixes to architectural violations reported by Evolith Core rule evaluators"
  },
  {
    "name": "evolith-composable-validate",
    "description": "Validate using the composable engine (GT-312). Supports multiple validation modes: SDLC, Architecture, Ruleset, ADR, Ad-hoc. Can combine modes."
  },
  {
    "name": "evolith-config-get",
    "description": "Get Evolith configuration value"
  },
  {
    "name": "evolith-config-set",
    "description": "Set Evolith configuration value"
  },
  {
    "name": "evolith-dora-metrics",
    "description": "Calculate DORA metrics approximations using Git log history"
  },
  {
    "name": "evolith-drift-detect",
    "description": "Detect architecture drift in a repository"
  },
  {
    "name": "evolith-evaluate",
    "description": "Evaluate a canonical EvaluationContext (gates, artifacts, rules, compliance) and return an EvaluationResult (ADR-0073 envelope). Stateless: product/tenant/initiative are opaque context only."
  },
  {
    "name": "evolith-gate-evaluate",
    "description": "Evaluate a specific SDLC phase gate"
  },
  {
    "name": "evolith-metrics",
    "description": "Get MCP server metrics (per-tool call counts, latency, failures)"
  },
  {
    "name": "evolith-moscow-create",
    "description": "Create a new MoSCoW prioritization analysis"
  },
  {
    "name": "evolith-moscow-list",
    "description": "List all MoSCoW analyses in a repository"
  },
  {
    "name": "evolith-moscow-load",
    "description": "Load an existing MoSCoW analysis"
  },
  {
    "name": "evolith-moscow-remove",
    "description": "Remove a specific item from a MoSCoW analysis"
  },
  {
    "name": "evolith-moscow-report",
    "description": "Generate a markdown report of a MoSCoW analysis"
  },
  {
    "name": "evolith-moscow-update",
    "description": "Update a specific item in a MoSCoW analysis"
  },
  {
    "name": "evolith-moscow-validate",
    "description": "Validate a MoSCoW analysis rules (e.g. 60/20/20 split)"
  },
  {
    "name": "evolith-phase-advance",
    "description": "Propose an SDLC phase transition by evaluating the current phase exit criteria"
  },
  {
    "name": "evolith-phase-artifacts-evaluate",
    "description": "Measure downstream-phase artifact completeness for a confirmed topology composition (advisory, ADR-0104 / DN-06 / GT-434). Stateless and non-binding: for a downstream phase (construction/quality/deployment) it compares the declared artifacts against the UNION of the universal per-phase artifacts and each topology's spec.phaseProfiles. Returns required/present/missing artifacts + completeness in the ADR-0073 success envelope. Produces the same result as POST /api/v1/architecture/evaluate-phase-artifacts and `evolith topology phase-artifacts`."
  },
  {
    "name": "evolith-satellite-adopt",
    "description": "Adopt an existing GitHub repository as an Evolith satellite. Returns an ADR-0073 output envelope."
  },
  {
    "name": "evolith-satellite-create",
    "description": "Create a new satellite repository on GitHub and register it with Evolith. Returns an ADR-0073 output envelope."
  },
  {
    "name": "evolith-satellite-list",
    "description": "List all registered Evolith satellites from the local satellite-registry.json."
  },
  {
    "name": "evolith-satellite-status",
    "description": "Get the status and details of a registered Evolith satellite by its ID."
  },
  {
    "name": "evolith-sdlc-handoff",
    "description": "Perform a phase gate handoff (e.g. phase-0 to phase-1)"
  },
  {
    "name": "evolith-sdlc-status",
    "description": "Get the current SDLC phase status"
  },
  {
    "name": "evolith-topology-get",
    "description": "Get a specific architecture topology by ID"
  },
  {
    "name": "evolith-topology-list",
    "description": "List all available architecture topologies in Evolith Core."
  },
  {
    "name": "evolith-topology-recommend",
    "description": "Recommend a topology composition from technical signals (advisory, ADR-0104 / GT-430). Stateless and non-binding: the Core RECOMMENDS (Discovery), the tenant CONFIRMS (Design). Returns the recommended composition + rationale in the ADR-0073 success envelope. Produces the same result as POST /api/v1/architecture/recommend-topology and `evolith topology recommend`."
  },
  {
    "name": "evolith-validate",
    "description": "Validate a satellite repository against Evolith rules. Supports end-to-end evaluation pipeline via manifest."
  }
];

export const GENERATED_RESOURCES: ApiResource[] = [
  {
    "uri": "evolith://agents",
    "name": "Agents",
    "description": "List of installed Evolith agents"
  },
  {
    "uri": "evolith://architecture/topologies",
    "name": "Architecture Topologies",
    "description": "List of all available architecture topologies"
  },
  {
    "uri": "evolith://core/info",
    "name": "Core Info",
    "description": "General information about the Evolith Core"
  },
  {
    "uri": "evolith://core/version",
    "name": "Core Version",
    "description": "Current Core schema version"
  },
  {
    "uri": "evolith://governance/version",
    "name": "Governance Version",
    "description": "Current governance schema version"
  },
  {
    "uri": "evolith://moscow/phase-0",
    "name": "MoSCoW Phase 0",
    "description": "MoSCoW prioritization matrix for discovery phase"
  },
  {
    "uri": "evolith://phase-gates",
    "name": "Phase Gates",
    "description": "Phase gate definitions and requirements"
  },
  {
    "uri": "evolith://repository/config",
    "name": "Repository Config",
    "description": "Repository evolith.yaml content"
  },
  {
    "uri": "evolith://rulesets",
    "name": "Rulesets",
    "description": "List of all available rulesets in Evolith Core"
  }
];
