// AUTO-GENERATED by scripts/gen-api-catalog.mjs from the live @beyondnet/evolith-mcp
// server (tools/list + resources/list). Do NOT edit by hand — run
// `npm run gen:api-catalog` to refresh. Source of truth: the MCP server (GT-460).

import type { ApiEntry, ApiResource } from './api.catalog';

export const GENERATED_TOOLS: ApiEntry[] = [
  {
    "name": "evolith-adr-create",
    "description": "Create a new Architecture Decision Record. Writes reference/architecture/adrs/<id>.md and updates the matrix."
  },
  {
    "name": "evolith-adr-get",
    "description": "Get the full details of a single ADR by id (e.g. ADR-0001) or number."
  },
  {
    "name": "evolith-adr-list",
    "description": "List all Architecture Decision Records (id, title, status, date)."
  },
  {
    "name": "evolith-adr-matrix",
    "description": "Get the ADR matrix summary (totals by status + recent ADRs)."
  },
  {
    "name": "evolith-adr-update",
    "description": "Update the status of an existing ADR (Proposed | Accepted | Deprecated | Superseded | Amended)."
  },
  {
    "name": "evolith-agent-install",
    "description": "Install a new Evolith agent"
  },
  {
    "name": "evolith-agent-list",
    "description": "List all installed Evolith agents"
  },
  {
    "name": "evolith-agent-remove",
    "description": "Remove an Evolith agent"
  },
  {
    "name": "evolith-agent-run",
    "description": "Run an intent through the Agent Runtime pipeline"
  },
  {
    "name": "evolith-agent-upgrade",
    "description": "Upgrade an existing Evolith agent"
  },
  {
    "name": "evolith-agent-validate",
    "description": "Validate a specific agent ruleset"
  },
  {
    "name": "evolith-architecture-validate",
    "description": "Validate repository architecture along the progressive maturity axis (modular-monolith → distributed-modules → microservices). Use deep=true for import graph analysis, layer violations, and coupling metrics."
  },
  {
    "name": "evolith-auto-fix",
    "description": "Apply automatic fixes to architectural violations reported by Evolith Core rule evaluators"
  },
  {
    "name": "evolith-composable-validate",
    "description": "Validate using the composable engine (GT-312). Supports multiple validation modes: SDLC, Architecture, Ruleset, ADR, Ad-hoc. Can combine modes."
  },
  {
    "name": "evolith-config-get",
    "description": "Get Evolith configuration value"
  },
  {
    "name": "evolith-config-set",
    "description": "Set Evolith configuration value"
  },
  {
    "name": "evolith-docs-scaffold",
    "description": "Scaffold the base documentation required by Evolith (README.md, AGENTS.md, MASTER_INDEX.md, evolith.yaml) into a target directory. Mirrors the CLI `docs` command. Mutative: writes files unless dryRun is set."
  },
  {
    "name": "evolith-dora-metrics",
    "description": "Calculate DORA metrics approximations using Git log history"
  },
  {
    "name": "evolith-drift-detect",
    "description": "Detect architecture drift in a repository"
  },
  {
    "name": "evolith-evaluate",
    "description": "Evaluate a canonical EvaluationContext (gates, artifacts, rules, compliance) and return an EvaluationResult (ADR-0073 envelope). Stateless: product/tenant/initiative are opaque context only."
  },
  {
    "name": "evolith-fixtures",
    "description": "Seed reproducible fixtures and sample data (evolith.yaml, ADRs, rulesets) for demos and tests. Mirrors the \"evolith fixtures\" CLI command."
  },
  {
    "name": "evolith-gate-evaluate",
    "description": "Evaluate a specific SDLC phase gate"
  },
  {
    "name": "evolith-init-batch",
    "description": "Non-interactive (batch/CI) initialization of an Evolith satellite. Parity with the CLI `init --config <json>` / `init --name … --yes` path, without prompts. Delegates scaffolding to the core-domain InitializeProjectUseCase. Returns an ADR-0073 output envelope with the initialization result (created artifacts, warnings, errors)."
  },
  {
    "name": "evolith-metrics",
    "description": "Get MCP server metrics (per-tool call counts, latency, failures)"
  },
  {
    "name": "evolith-moscow-create",
    "description": "Create a new MoSCoW prioritization analysis"
  },
  {
    "name": "evolith-moscow-list",
    "description": "List all MoSCoW analyses in a repository"
  },
  {
    "name": "evolith-moscow-load",
    "description": "Load an existing MoSCoW analysis"
  },
  {
    "name": "evolith-moscow-remove",
    "description": "Remove a specific item from a MoSCoW analysis"
  },
  {
    "name": "evolith-moscow-report",
    "description": "Generate a markdown report of a MoSCoW analysis"
  },
  {
    "name": "evolith-moscow-update",
    "description": "Update a specific item in a MoSCoW analysis"
  },
  {
    "name": "evolith-moscow-validate",
    "description": "Validate a MoSCoW analysis rules (e.g. 60/20/20 split)"
  },
  {
    "name": "evolith-pattern-get",
    "description": "Get one canonical pattern (PAT-NNNN) by id, case-insensitively. Returns the full record — problem, forces, solution, applicability per topology, governing ADRs and enforcing rules — in the ADR-0073 success envelope."
  },
  {
    "name": "evolith-pattern-list",
    "description": "List the canonical architectural patterns and anti-patterns (PAT-NNNN) published by Evolith Core, optionally filtered by category, kind, applicable topology, or whether a rule already enforces them. Returns the records in the ADR-0073 success envelope."
  },
  {
    "name": "evolith-pattern-list-by-topology",
    "description": "List the canonical patterns that apply to a topology, how strongly (required → recommended → optional) and — the point of the query — which rules each one imposes (`enforcedBy`). `not-applicable` entries are excluded. Returns the applications in the ADR-0073 success envelope."
  },
  {
    "name": "evolith-phase-advance",
    "description": "Propose an SDLC phase transition by evaluating the current phase exit criteria"
  },
  {
    "name": "evolith-phase-artifacts-evaluate",
    "description": "Measure downstream-phase artifact completeness for a confirmed topology composition (advisory, ADR-0104 / DN-06 / GT-434). Stateless and non-binding: for a downstream phase (construction/quality/deployment) it compares the declared artifacts against the UNION of the universal per-phase artifacts and each topology's spec.phaseProfiles. Returns required/present/missing artifacts + completeness in the ADR-0073 success envelope. Produces the same result as POST /api/v1/architecture/evaluate-phase-artifacts and `evolith topology phase-artifacts`."
  },
  {
    "name": "evolith-satellite-adopt",
    "description": "Adopt an existing GitHub repository as an Evolith satellite. Returns an ADR-0073 output envelope."
  },
  {
    "name": "evolith-satellite-create",
    "description": "Create a new satellite repository on GitHub and register it with Evolith. Returns an ADR-0073 output envelope."
  },
  {
    "name": "evolith-satellite-list",
    "description": "List all registered Evolith satellites from the local satellite-registry.json."
  },
  {
    "name": "evolith-satellite-status",
    "description": "Get the status and details of a registered Evolith satellite by its ID."
  },
  {
    "name": "evolith-scaffold",
    "description": "Scaffold an Evolith satellite along the progressive maturity axis (phase 1 modular-monolith → 2 distributed-modules → 3 microservices). Phase 1 generates a standard SPA; phases 2–3 a Module Federation host + remotes, plus the NestJS Service API, transversal shells and DDD bounded-context libraries. Mutative: writes the Nx workspace under <path>/src. MCP parity with `evolith scaffold`."
  },
  {
    "name": "evolith-sdlc-generate",
    "description": "Generate a Hexagonal Architecture scaffold from a Mermaid classDiagram in a Markdown DDD model (parity with the CLI `sdlc generate`). Supply the model inline via `model` or as a file via `from`. Writes files unless `dryRun` is true."
  },
  {
    "name": "evolith-sdlc-handoff",
    "description": "Perform a phase gate handoff (e.g. phase-0 to phase-1)"
  },
  {
    "name": "evolith-sdlc-status",
    "description": "Get the current SDLC phase status"
  },
  {
    "name": "evolith-topology-get",
    "description": "Get a specific architecture topology by ID"
  },
  {
    "name": "evolith-topology-list",
    "description": "List all available architecture topologies in Evolith Core."
  },
  {
    "name": "evolith-topology-recommend",
    "description": "Recommend a topology composition from technical signals (advisory, ADR-0104 / GT-430). Stateless and non-binding: the Core RECOMMENDS (Discovery), the tenant CONFIRMS (Design). Returns the recommended composition + rationale in the ADR-0073 success envelope. Produces the same result as POST /api/v1/architecture/recommend-topology and `evolith topology recommend`."
  },
  {
    "name": "evolith-upgrade-apply",
    "description": "Apply a satellite upgrade from the upstream Evolith core. Writes files into the satellite. Set force=true to proceed when breaking changes are detected."
  },
  {
    "name": "evolith-upgrade-plan",
    "description": "Plan a satellite upgrade against the upstream Evolith core (read-only / dry-run). Computes the change plan, breaking changes and estimated risk without writing any files."
  },
  {
    "name": "evolith-validate",
    "description": "Validate a satellite repository against Evolith rules. Supports end-to-end evaluation pipeline via manifest."
  }
];

export const GENERATED_RESOURCES: ApiResource[] = [
  {
    "uri": "evolith://agents",
    "name": "Agents",
    "description": "List of installed Evolith agents"
  },
  {
    "uri": "evolith://architecture/patterns",
    "name": "Architecture Patterns",
    "description": "Canonical architectural patterns and anti-patterns (PAT-NNNN) with their applicability and enforcing rules"
  },
  {
    "uri": "evolith://architecture/topologies",
    "name": "Architecture Topologies",
    "description": "List of all available architecture topologies"
  },
  {
    "uri": "evolith://capabilities",
    "name": "Capability Manifest",
    "description": "Versioned capability manifest of the Evolith Core evaluation engine (evaluationKinds, engines, surfaces, supportedConsumers)"
  },
  {
    "uri": "evolith://contracts",
    "name": "Machine Contracts",
    "description": "Machine-readable schema/contract set the Core publishes for external consumers"
  },
  {
    "uri": "evolith://core/info",
    "name": "Core Info",
    "description": "General information about the Evolith Core"
  },
  {
    "uri": "evolith://core/version",
    "name": "Core Version",
    "description": "Current Core schema version"
  },
  {
    "uri": "evolith://governance/version",
    "name": "Governance Version",
    "description": "Current governance schema version"
  },
  {
    "uri": "evolith://moscow/phase-0",
    "name": "MoSCoW Phase 0",
    "description": "MoSCoW prioritization matrix for discovery phase"
  },
  {
    "uri": "evolith://phase-gates",
    "name": "Phase Gates",
    "description": "Phase gate definitions and requirements"
  },
  {
    "uri": "evolith://repository/config",
    "name": "Repository Config",
    "description": "Repository evolith.yaml content"
  },
  {
    "uri": "evolith://rulesets",
    "name": "Rulesets",
    "description": "List of all available rulesets in Evolith Core"
  }
];
