// GT-460: the MCP tools/resources surface is generated from the live
// @beyondnet/evolith-mcp server (scripts/gen-api-catalog.mjs) so `api --list`
// never drifts from reality. Refresh with `npm run gen:api-catalog`.
import { GENERATED_TOOLS, GENERATED_RESOURCES } from './api.catalog.generated';
// GT-583: the per-operation schemas come from the CAPABILITY MANIFEST
// (`buildCapabilityManifest().operations`), generated by
// `.harness/scripts/generate-capability-operations.mjs`. Refresh with that
// command; `--check` is the CI drift guard.
import { GENERATED_TOOL_SCHEMAS } from './api.catalog.tool-schemas.generated';

export interface ApiCategory {
  name: string;
  label: string;
  description: string;
}

export interface ApiEntry {
  name: string;
  description: string;
}

export interface ApiResource {
  uri: string;
  name: string;
  description: string;
}

export interface ToolSchema {
  description: string;
  inputSchema: object;
  outputSchema: object;
}

export interface ResourceSchema {
  description: string;
  mimeType: string;
}

export interface CommandSchema {
  description: string;
  options: Array<{ flags: string; description: string }>;
}

// Tools and resources come from the live MCP server (GT-460). Counts are
// derived from the arrays, never hardcoded, so they can never disagree.
export const TOOLS: ApiEntry[] = GENERATED_TOOLS;
export const RESOURCES: ApiResource[] = GENERATED_RESOURCES;

export const SCHEMAS: ApiEntry[] = [
  { name: 'gate-evidence', description: 'Schema for gate evaluation evidence' },
  { name: 'phase-transition', description: 'Schema for phase transition requests' },
  { name: 'adr-record', description: 'Schema for Architecture Decision Records' },
  { name: 'ruleset-schema', description: 'Base schema for ruleset definitions' },
  { name: 'acl-schema', description: 'Anti-Corruption Layer validation schema' },
  { name: 'build-vs-compose', description: 'Build vs Compose evidence validation' },
  { name: 'moscow-matrix', description: 'MoSCoW prioritization matrix schema' },
  { name: 'agent-config', description: 'Agent configuration schema' },
];

export const COMMANDS: ApiEntry[] = [
  { name: 'init', description: 'Initialize new Evolith project' },
  { name: 'validate', description: 'Validate project against governance' },
  { name: 'gate', description: 'Phase gate evaluation and status' },
  { name: 'sdlc', description: 'SDLC phase management' },
  { name: 'adr', description: 'ADR registry and management' },
  { name: 'docs', description: 'Documentation scaffolding' },
  { name: 'scaffold', description: 'Architecture pattern scaffolding' },
  { name: 'drift', description: 'Architecture drift detection' },
  { name: 'completion', description: 'Shell completion and hooks' },
  { name: 'fixtures', description: 'Generate test fixtures' },
  { name: 'history', description: 'Project history and DORA metrics' },
  { name: 'profile', description: 'CLI configuration profiles' },
  { name: 'upgrade', description: 'Upgrade Evolith project' },
  { name: 'api', description: 'Browse API surface (this command)' },
];

// Counts are derived from the arrays above (never hardcoded) so the summary can
// never disagree with the lists it advertises (GT-460).
export const CATEGORIES: ApiCategory[] = [
  { name: 'tools', label: 'MCP Tools', description: `${TOOLS.length} available operations` },
  { name: 'resources', label: 'MCP Resources', description: `${RESOURCES.length} available resources` },
  { name: 'schemas', label: 'Phase-Gate Schemas', description: `${SCHEMAS.length} validation schemas` },
  { name: 'commands', label: 'CLI Commands', description: `${COMMANDS.length} native commands` },
];

/**
 * GT-583 — the per-operation schema catalog, GENERATED from the capability
 * manifest. It replaced a hand-written map of THREE entries that claimed to
 * describe an MCP surface of fifty tools, keyed 'gate-evaluate' while the tool
 * is named 'evolith-gate-evaluate', and naming one operation ('agent-create')
 * that has never existed. Every `evolith api --inspect` of a real tool
 * answered 'not found' while this map claimed otherwise.
 *
 * Regenerate: node .harness/scripts/generate-capability-operations.mjs
 */
export const TOOL_SCHEMAS: Record<string, ToolSchema> = GENERATED_TOOL_SCHEMAS;

export const RESOURCE_SCHEMAS: Record<string, ResourceSchema> = {
  'evolith://rulesets': {
    description: 'List of all available rulesets in Evolith Core',
    mimeType: 'application/json',
  },
  'evolith://phase-gates': {
    description: 'Phase gate definitions and requirements',
    mimeType: 'application/json',
  },
  'evolith://core/info': {
    description: 'General information about the Evolith Core',
    mimeType: 'application/json',
  },
};

export const COMMAND_SCHEMAS: Record<string, CommandSchema> = {
  'init': {
    description: 'Initialize a new Evolith project',
    options: [
      { flags: '-n, --name <name>', description: 'Project name' },
      { flags: '-t, --type <type>', description: 'Project type (library, app, api)' },
      { flags: '-r, --runtime <runtime>', description: 'Runtime (nodejs, dotnet, python)' },
      { flags: '--dry-run', description: 'Show what would be created' },
    ],
  },
  'validate': {
    description: 'Validate project against governance rules',
    options: [
      { flags: '--ruleset <name>', description: 'Specific ruleset to validate against' },
      { flags: '--strict', description: 'Fail on warnings' },
      { flags: '--report', description: 'Output validation report' },
    ],
  },
  'gate': {
    description: 'Phase gate evaluation and status commands',
    options: [
      { flags: 'evaluate', description: 'Evaluate gate compliance' },
      { flags: 'status', description: 'Show current gate status' },
      { flags: '--phase <phase>', description: 'Specific phase to evaluate' },
    ],
  },
};
