/**
 * Generates a Hexagonal Architecture scaffold from a parsed ClassDiagram.
 *
 * Output layout (relative to targetDir):
 *   src/domain/entities/          ← Entity, Aggregate
 *   src/domain/value-objects/     ← ValueObject
 *   src/domain/repositories/      ← Repository interfaces  (I{Name}Repository.ts)
 *   src/domain/services/          ← Service interfaces
 *   src/infrastructure/persistence/  ← Repository stub implementations
 */

import * as path from 'path';
import * as fs from 'fs-extra';
import type { ClassDiagram, ClassDef, PropertyDef, MethodDef, ParamDef } from './mermaid-class-parser';

export interface ScaffoldResult {
  created: string[];
  skipped: string[];
}

// ── template helpers ──────────────────────────────────────────────────────────

function indent(n: number, s: string): string {
  const pad = '  '.repeat(n);
  return s
    .split('\n')
    .map(l => (l.trim() ? pad + l : l))
    .join('\n');
}

function renderParams(params: ParamDef[]): string {
  return params.map(p => `${p.name}: ${p.type}`).join(', ');
}

function renderMethodStub(m: MethodDef, isAsync = false): string {
  const sig = `${m.name}(${renderParams(m.params)}): ${isAsync ? `Promise<${m.returnType}>` : m.returnType}`;
  return [
    `${m.visibility === 'public' ? '' : m.visibility + ' '}${isAsync ? 'async ' : ''}${sig} {`,
    `  throw new Error('Not implemented: ${m.name}');`,
    `}`,
  ].join('\n');
}

function renderConstructorParam(p: PropertyDef): string {
  const access = p.visibility === 'public' ? 'public readonly ' : 'private ';
  return `${access}${p.name}: ${p.type}`;
}

// ── per-stereotype generators ─────────────────────────────────────────────────

function generateEntity(cls: ClassDef): string {
  const ctorParams = cls.properties.map(renderConstructorParam).join(',\n    ');
  const methods = cls.methods
    .map(m => indent(1, renderMethodStub(m)))
    .join('\n\n');

  return [
    `/**`,
    ` * ${cls.name} — Domain Entity`,
    ` * Generated by: evolith sdlc generate`,
    ` * Stereotype:   ${cls.stereotype}`,
    ` */`,
    `export class ${cls.name} {`,
    ctorParams
      ? `  constructor(\n    ${ctorParams},\n  ) {}`
      : `  constructor() {}`,
    methods ? `\n${methods}` : '',
    `}`,
    ``,
  ].filter(l => l !== undefined).join('\n');
}

function generateValueObject(cls: ClassDef): string {
  const ctorParams = cls.properties.map(renderConstructorParam).join(',\n    ');
  const methods = cls.methods
    .filter(m => m.name !== 'validate')
    .map(m => indent(1, renderMethodStub(m)))
    .join('\n\n');

  return [
    `/**`,
    ` * ${cls.name} — Value Object`,
    ` * Generated by: evolith sdlc generate`,
    ` */`,
    `export class ${cls.name} {`,
    ctorParams
      ? `  constructor(\n    ${ctorParams},\n  ) {\n    this.validate();\n  }`
      : `  constructor() {\n    this.validate();\n  }`,
    ``,
    `  private validate(): void {`,
    `    // Validation rules for ${cls.name} should be implemented here`,
    `    // For example: if (!this.id) throw new Error('Invalid ID');`,
    `  }`,
    methods ? `\n${methods}` : '',
    `}`,
    ``,
  ].join('\n');
}

function generateAggregate(cls: ClassDef): string {
  const ctorParams = cls.properties.map(renderConstructorParam).join(',\n    ');
  const methods = cls.methods
    .map(m => indent(1, renderMethodStub(m)))
    .join('\n\n');

  return [
    `/**`,
    ` * ${cls.name} — Aggregate Root`,
    ` * Generated by: evolith sdlc generate`,
    ` */`,
    `export class ${cls.name} {`,
    `  private readonly _domainEvents: unknown[] = [];`,
    ``,
    ctorParams
      ? `  constructor(\n    ${ctorParams},\n  ) {}`
      : `  constructor() {}`,
    ``,
    `  get domainEvents(): unknown[] {`,
    `    return [...this._domainEvents];`,
    `  }`,
    ``,
    `  protected addDomainEvent(event: unknown): void {`,
    `    this._domainEvents.push(event);`,
    `  }`,
    methods ? `\n${methods}` : '',
    `}`,
    ``,
  ].join('\n');
}

function generateRepositoryInterface(cls: ClassDef, entityName: string): string {
  const methodSigs = cls.methods.map(m => {
    const sig = `${m.name}(${renderParams(m.params)}): Promise<${m.returnType === 'void' ? 'void' : m.returnType}>`;
    return `  ${sig};`;
  });

  // Always include at least findById and save
  const hasFindById = cls.methods.some(m => m.name === 'findById');
  const hasSave = cls.methods.some(m => m.name === 'save');
  if (!hasFindById) methodSigs.unshift(`  findById(id: string): Promise<${entityName} | null>;`);
  if (!hasSave) methodSigs.push(`  save(entity: ${entityName}): Promise<void>;`);

  return [
    `/**`,
    ` * I${cls.name} — Repository Interface`,
    ` * Generated by: evolith sdlc generate`,
    ` */`,
    `import type { ${entityName} } from '../entities/${entityName}';`,
    ``,
    `export interface I${cls.name} {`,
    ...methodSigs,
    `}`,
    ``,
  ].join('\n');
}

function generateRepositoryImpl(cls: ClassDef, entityName: string): string {
  const methods = [
    `  async findById(id: string): Promise<${entityName} | null> {`,
    `    throw new Error('Not implemented: findById');`,
    `  }`,
    ``,
    `  async save(entity: ${entityName}): Promise<void> {`,
    `    throw new Error('Not implemented: save');`,
    `  }`,
  ];

  cls.methods.forEach(m => {
    if (m.name === 'findById' || m.name === 'save') return;
    methods.push('');
    methods.push(`  async ${m.name}(${renderParams(m.params)}): Promise<${m.returnType === 'void' ? 'void' : m.returnType}> {`);
    methods.push(`    throw new Error('Not implemented: ${m.name}');`);
    methods.push(`  }`);
  });

  return [
    `/**`,
    ` * ${cls.name} — Repository Implementation (stub)`,
    ` * Generated by: evolith sdlc generate`,
    ` * Replace with real persistence logic (TypeORM, Prisma, etc.)`,
    ` */`,
    `import type { ${entityName} } from '../../domain/entities/${entityName}';`,
    `import type { I${cls.name} } from '../../domain/repositories/I${cls.name}';`,
    ``,
    `export class ${cls.name} implements I${cls.name} {`,
    ...methods,
    `}`,
    ``,
  ].join('\n');
}

function generateService(cls: ClassDef): string {
  const methods = cls.methods
    .map(m => indent(1, renderMethodStub(m, true)))
    .join('\n\n');

  return [
    `/**`,
    ` * ${cls.name} — Domain Service`,
    ` * Generated by: evolith sdlc generate`,
    ` */`,
    `export class ${cls.name} {`,
    methods || `  // Domain service methods should be implemented here`,
    `}`,
    ``,
  ].join('\n');
}

// ── folder mapping ────────────────────────────────────────────────────────────

function resolveEntityNameForRepo(cls: ClassDef, diagram: ClassDiagram): string {
  // Look for a relationship from this Repository to an Entity/Aggregate
  const rel = diagram.relationships.find(r => r.from === cls.name || r.to === cls.name);
  if (rel) {
    const other = rel.from === cls.name ? rel.to : rel.from;
    const otherCls = diagram.classes.find(c => c.name === other);
    if (otherCls && (otherCls.stereotype === 'Entity' || otherCls.stereotype === 'Aggregate')) {
      return otherCls.name;
    }
  }
  // Fallback: strip 'Repository' suffix
  return cls.name.replace(/Repository$/i, '') || cls.name;
}

// ── public API ────────────────────────────────────────────────────────────────

export async function scaffoldHexagonal(
  diagram: ClassDiagram,
  targetDir: string,
  dryRun = false,
): Promise<ScaffoldResult> {
  const created: string[] = [];
  const skipped: string[] = [];

  async function write(relPath: string, content: string): Promise<void> {
    const abs = path.join(targetDir, relPath);
    if (await fs.pathExists(abs)) {
      skipped.push(relPath);
      return;
    }
    if (!dryRun) {
      await fs.ensureDir(path.dirname(abs));
      await fs.writeFile(abs, content, 'utf-8');
    }
    created.push(relPath);
  }

  for (const cls of diagram.classes) {
    switch (cls.stereotype) {
      case 'Entity':
        await write(
          `src/domain/entities/${cls.name}.ts`,
          generateEntity(cls),
        );
        break;

      case 'Aggregate':
        await write(
          `src/domain/entities/${cls.name}.ts`,
          generateAggregate(cls),
        );
        break;

      case 'ValueObject':
        await write(
          `src/domain/value-objects/${cls.name}.ts`,
          generateValueObject(cls),
        );
        break;

      case 'Repository': {
        const entityName = resolveEntityNameForRepo(cls, diagram);
        await write(
          `src/domain/repositories/I${cls.name}.ts`,
          generateRepositoryInterface(cls, entityName),
        );
        await write(
          `src/infrastructure/persistence/${cls.name}.ts`,
          generateRepositoryImpl(cls, entityName),
        );
        break;
      }

      case 'Service':
        await write(
          `src/domain/services/${cls.name}.ts`,
          generateService(cls),
        );
        break;

      default:
        // unknown stereotype — still scaffold as a plain class under entities
        await write(
          `src/domain/entities/${cls.name}.ts`,
          generateEntity(cls),
        );
    }
  }

  return { created, skipped };
}
