import * as fs from 'fs';
import * as path from 'path';
import { tmpdir } from 'node:os';
import { resolveRulesets } from './rulesets-resolver';

// `fs`'s own exports are non-configurable, so spying needs a mutable module
// object. Every function keeps the REAL implementation unless a test overrides
// it — these tests exercise the resolver against the real filesystem by default.
jest.mock('fs', () => {
  const actual = jest.requireActual('fs');
  return {
    ...actual,
    existsSync: jest.fn(actual.existsSync),
    readdirSync: jest.fn(actual.readdirSync),
  };
});

const actualFs = jest.requireActual<typeof fs>('fs');

/**
 * GT-562 — the BUNDLED resolution path (`resolveRulesets()` with no `--core`)
 * was entirely uncovered, even though it is the path EVERY installed user takes:
 * a plain `evolith validate` with no override resolves its corpus by walking up
 * from `__dirname` looking for the CLI package root.
 *
 * The failure mode this family has produced before (GT-474, GT-566) is never a
 * crash — it is resolving a directory that merely SHARES A NAME with the corpus
 * and then reporting "0 rules, all good". So these tests assert on what was
 * resolved and on the corpus actually being there, not merely that a string came
 * back.
 *
 * ## Why the bundled cases drive a SYNTHETIC filesystem
 *
 * These cases originally read the real bundled tree at `src/sdk/cli/rulesets/`.
 * That tree is a BUILD ARTIFACT: `rulesets/*` is gitignored and generated by
 * `scripts/copy-rulesets.js` on the CLI's `prebuild`. CI installs with `npm ci`
 * at the workspace root, which never triggers that prebuild, so resolution
 * correctly failed and these tests failed with it. They passed locally only on
 * trees carrying a copy from an earlier build.
 *
 * GT-643 — one case was left reading the real tree and survived only because
 * three files a test had written were committed under `rulesets/agents/`, which
 * kept the DIRECTORY present in a clean checkout even though its contents were
 * never a corpus. Deleting that residue turned the walk into one that never
 * reaches a `…/rulesets` at all, and the case failed for a reason that had
 * nothing to do with what it asserts. It now drives the synthetic tree too.
 *
 * `findBundledRulesets` walks up from `__dirname`, which cannot be redirected at
 * a fixture, so the walk is driven over an in-memory tree through the already
 * mocked `fs`. The mock stands in for the FILESYSTEM, not for the resolver: the
 * real walk, the real `package.json` + corpus-marker qualification and the real
 * ordering all still execute. It is also strictly stronger than reading the real
 * tree, because it can pose the case that matters — a non-corpus `rulesets/`
 * sitting BELOW a real one — which a developer checkout cannot reproduce.
 */

/** Absolute paths of the directories the synthetic tree contains. */
function mountSyntheticTree(tree: Readonly<Record<string, readonly string[]>>): void {
  (fs.existsSync as jest.Mock).mockImplementation((p: fs.PathLike) => {
    const key = String(p);
    if (key in tree) return true;
    // A `package.json` exists exactly where the tree declares one.
    return Object.prototype.hasOwnProperty.call(tree, key);
  });
  (fs.readdirSync as jest.Mock).mockImplementation((p: fs.PathLike) => {
    const entries = tree[String(p)];
    if (!entries) {
      const err = new Error(`ENOENT: no such file or directory, scandir '${String(p)}'`) as NodeJS.ErrnoException;
      err.code = 'ENOENT';
      throw err;
    }
    return entries as string[];
  });
}

describe('resolveRulesets — bundled corpus resolution', () => {
  beforeEach(() => {
    (fs.existsSync as jest.Mock).mockImplementation(actualFs.existsSync);
    (fs.readdirSync as jest.Mock).mockImplementation(actualFs.readdirSync);
  });

  it('resolves the corpus bundled in the CLI package when no --core override is given', () => {
    // The nearest ancestor of `__dirname` that has BOTH a package.json and a
    // corpus-shaped `rulesets/` is the CLI package root.
    const pkgRoot = path.resolve(__dirname, '..', '..', '..');
    mountSyntheticTree({
      [path.join(pkgRoot, 'package.json')]: [],
      [path.join(pkgRoot, 'rulesets')]: ['architecture', 'topologies', 'opa', 'schema'],
    });

    const resolved = resolveRulesets();

    expect(resolved.source).toBe('bundled');
    expect(resolved.rulesetsRoot).toBe(path.join(pkgRoot, 'rulesets'));
    // `coreRoot` is the package root, `rulesetsRoot` the corpus inside it; the
    // TopologyCatalogService appends `rulesets/...` to `coreRoot`, so the two
    // must stay in this parent/child relationship.
    expect(path.dirname(resolved.rulesetsRoot)).toBe(resolved.coreRoot);
    expect(resolved.coreRoot).toBe(pkgRoot);
  });

  it('walks past a `rulesets` dir that only holds `agents`, instead of latching onto the name', () => {
    // GT-566, posed directly: the CLI package root carries the satellite-side
    // `rulesets/agents` tree and NO corpus, while an ancestor carries the real
    // corpus. Name-based resolution stops at the first and reports zero rules;
    // content-qualified resolution must continue up.
    const pkgRoot = path.resolve(__dirname, '..', '..', '..');
    const ancestor = path.resolve(pkgRoot, '..', '..', '..');
    mountSyntheticTree({
      [path.join(pkgRoot, 'package.json')]: [],
      [path.join(pkgRoot, 'rulesets')]: ['agents'],
      [path.join(ancestor, 'package.json')]: [],
      [path.join(ancestor, 'rulesets')]: ['architecture', 'topologies'],
    });

    const resolved = resolveRulesets();

    expect(resolved.rulesetsRoot).toBe(path.join(ancestor, 'rulesets'));
    expect(resolved.coreRoot).toBe(ancestor);
  });

  it('resolves a directory that really holds canonical ruleset families, not just any `rulesets` dir', () => {
    const pkgRoot = path.resolve(__dirname, '..', '..', '..');
    mountSyntheticTree({
      [path.join(pkgRoot, 'package.json')]: [],
      [path.join(pkgRoot, 'rulesets')]: ['architecture', 'topologies', 'adr'],
    });

    const { rulesetsRoot } = resolveRulesets();

    // Content-qualified: this is the check that stops the satellite-side
    // `rulesets/agents` tree from shadowing the real corpus.
    const entries = fs.readdirSync(rulesetsRoot);
    expect(entries).toEqual(
      expect.arrayContaining([expect.stringMatching(/^(architecture|topologies|adr|opa|schema)$/)]),
    );
  });

  it('treats an empty override string as "no override" and falls through to the bundled corpus', () => {
    // `--core ""` (or an unset profile value read as '') must not be taken as a
    // real override — resolving `""` would resolve to cwd, which this resolver
    // deliberately never falls back to.
    const pkgRoot = path.resolve(__dirname, '..', '..', '..');
    mountSyntheticTree({
      [path.join(pkgRoot, 'package.json')]: [],
      [path.join(pkgRoot, 'rulesets')]: ['architecture'],
    });

    expect(resolveRulesets('   ').source).toBe('bundled');
  });

  it('reports an actionable failure, naming every path probed, when an override holds no corpus', () => {
    const empty = actualFs.mkdtempSync(path.join(tmpdir(), 'evolith-nocorpus-'));
    try {
      expect(() => resolveRulesets(empty)).toThrow(new RegExp(empty.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
    } finally {
      actualFs.rmSync(empty, { recursive: true, force: true });
    }
  });

  it('skips an unreadable candidate directory instead of crashing the whole resolution', () => {
    // A directory that exists but cannot be listed (permissions, a dangling
    // mount) must be treated as "not a corpus" and the walk must continue —
    // otherwise an unrelated unreadable ancestor takes the CLI down.
    // Over the SYNTHETIC tree, not the checkout: this case used to read the real
    // one, where the only thing guaranteeing a `…/rulesets` directory existed was
    // committed test residue (GT-643). Once that was deleted the walk never
    // reached a candidate, the EACCES was never raised, and the assertion below
    // failed for a reason unrelated to unreadable directories.
    const pkgRoot = path.resolve(__dirname, '..', '..', '..');
    mountSyntheticTree({
      [path.join(pkgRoot, 'package.json')]: [],
      [path.join(pkgRoot, 'rulesets')]: ['architecture'],
    });
    const syntheticReaddir = (fs.readdirSync as jest.Mock).getMockImplementation() as (...a: unknown[]) => unknown;

    let threwAtLeastOnce = false;
    (fs.readdirSync as jest.Mock).mockImplementation((p: fs.PathLike, ...rest: unknown[]) => {
      if (String(p).endsWith(`${path.sep}rulesets`) && !threwAtLeastOnce) {
        threwAtLeastOnce = true;
        const err = new Error('EACCES: permission denied') as NodeJS.ErrnoException;
        err.code = 'EACCES';
        throw err;
      }
      return syntheticReaddir(p, ...rest);
    });

    // Resolution either continues up the tree to another package root or throws
    // the actionable "Rulesets not found" error — never an EACCES escaping raw.
    try {
      const resolved = resolveRulesets();
      expect(resolved.source).toBe('bundled');
    } catch (err) {
      expect((err as Error).message).toContain('Rulesets not found');
    }
    expect(threwAtLeastOnce).toBe(true);
  });

  it('gives up with an actionable message rather than falling back to cwd when nothing is bundled', () => {
    // The resolver's stated contract is "never falls back to process.cwd()".
    // Simulate a CLI installed without its corpus: nothing qualifies anywhere.
    (fs.existsSync as jest.Mock).mockReturnValue(false);

    expect(() => resolveRulesets()).toThrow(/Rulesets not found/);
    expect(() => resolveRulesets()).toThrow(/--core/);
  });
});
