{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "evolith-core-api.fullname" . }}
  labels:
    app: {{ include "evolith-core-api.name" . }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app: {{ include "evolith-core-api.name" . }}
{{- end }}
