{{- if .Values.opa.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "evolith-bff.fullname" . }}-opa-config
  labels:
    app: {{ include "evolith-bff.name" . }}
data:
  config.yaml: |
    services:
      s3:
        url: {{ .Values.opa.bundle.url | quote }}
        {{- if .Values.opa.bundle.credentials.existingSecretName }}
        credentials:
          s3_signing:
            environment_credentials: {}
        {{- end }}
    bundles:
      authz:
        service: s3
        resource: {{ .Values.opa.bundle.resource | quote }}
        persist: true
        polling:
          min_delay_seconds: {{ .Values.opa.bundle.pollingMinDelaySeconds }}
          max_delay_seconds: {{ .Values.opa.bundle.pollingMaxDelaySeconds }}
        {{- if .Values.opa.bundle.signing.enabled }}
        signing:
          keyid: {{ .Values.opa.bundle.signing.keyId | quote }}
          scope: {{ .Values.opa.bundle.signing.scope | quote }}
        {{- end }}
    decision_logs:
      console: true
{{- end }}
