import assert from 'node:assert/strict';
import test from 'node:test';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import {
  GENERATED_DOC_EXCLUSIONS,
  validateEntries,
  partitionByExclusions,
  formatExclusionReport,
} from './generated-doc-exclusions.mjs';

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../..');
const SUITE = path.join(REPO_ROOT, '.harness/scripts/ci/suites/bilingual-suite.mjs');

/** Run the real guard and return { code, out }. */
function runGuard() {
  try {
    const out = execFileSync('node', [SUITE], { cwd: REPO_ROOT, encoding: 'utf8', stdio: 'pipe' });
    return { code: 0, out };
  } catch (err) {
    return { code: err.status ?? 1, out: `${err.stdout ?? ''}${err.stderr ?? ''}` };
  }
}

// --- The rules the table must obey -------------------------------------------

test('every declared exclusion names a generator and a reason', () => {
  assert.doesNotThrow(() => validateEntries());
  for (const e of GENERATED_DOC_EXCLUSIONS) {
    assert.ok(e.generator?.trim(), `${e.id} must name its generator`);
    assert.ok(e.reason?.trim(), `${e.id} must state why parity does not apply`);
  }
});

test('an exclusion without a generator is rejected, not silently accepted', () => {
  assert.throws(
    () => validateEntries([{ id: 'x', reason: 'because', matches: () => true, marker: 'm' }]),
    /has no `generator`/,
  );
});

test('an exclusion without a reason is rejected', () => {
  assert.throws(
    () => validateEntries([{ id: 'x', generator: 'g.mjs', matches: () => true, marker: 'm' }]),
    /has no `reason`/,
  );
});

test('an exclusion that proves membership neither by marker nor by pinned count is rejected', () => {
  assert.throws(
    () => validateEntries([{ id: 'x', generator: 'g.mjs', reason: 'r', matches: () => true }]),
    /neither `marker` nor `expectedFiles`/,
  );
});

// --- Membership is proven, not asserted --------------------------------------

test('a file inside a marker-verified tree that lacks the marker stays IN SCOPE', () => {
  const entries = [
    { id: 'wiki', generator: 'sync-wiki.mjs', reason: 'mirror', matches: (r) => r.startsWith('w/'), marker: 'AUTOGEN' },
  ];
  const files = ['w/real.md', 'w/handwritten.md'];
  const read = (r) => (r === 'w/real.md' ? 'AUTOGEN header\n' : 'I wrote this by hand\n');

  const p = partitionByExclusions(files, read, entries);
  assert.deepEqual(p.excluded[0].files, ['w/real.md']);
  assert.deepEqual(p.inScope, ['w/handwritten.md'], 'unstamped file must not be exempted');
  assert.match(p.refusals.join('\n'), /do NOT carry the marker/);
});

test('a count-pinned tree that changed shape has its exclusion REFUSED entirely', () => {
  const entries = [
    { id: 'okf', generator: 'okf.mjs', reason: 'projection', matches: (r) => r.startsWith('okf/'), expectedFiles: 2 },
  ];
  const p = partitionByExclusions(['okf/a.md', 'okf/b.md', 'okf/surprise.md'], () => '', entries);
  assert.deepEqual(p.excluded[0].files, [], 'refused exclusion exempts nothing');
  assert.equal(p.inScope.length, 3, 'all files fall back into scope so the guard goes red');
  assert.match(p.refusals.join('\n'), /EXCLUSION REFUSED/);
});

// --- Exclusions are reported, never hidden -----------------------------------

test('the report names each exclusion, its count, its generator and its reason', () => {
  const entries = [
    { id: 'wiki', generator: 'sync-wiki.mjs', reason: 'published mirror', matches: (r) => r.startsWith('w/'), marker: 'AUTOGEN' },
  ];
  const report = formatExclusionReport(partitionByExclusions(['w/a.md'], () => 'AUTOGEN', entries));
  assert.match(report, /1 file\(s\) exempt/);
  assert.match(report, /wiki: 1 file\(s\)/);
  assert.match(report, /generated by sync-wiki\.mjs/);
  assert.match(report, /published mirror/);
});

test('the live guard prints its exclusion ledger on every run', () => {
  const { out } = runGuard();
  assert.match(out, /declared exclusions \(\d+ file\(s\) exempt/);
  for (const e of GENERATED_DOC_EXCLUSIONS) {
    assert.match(out, new RegExp(`${e.id}: \\d+ file\\(s\\)`), `${e.id} must appear in the ledger`);
  }
});

// --- THE POINT: the guard still catches a genuine unpaired document ----------
//
// This is the regression the whole change exists to protect. If an exclusion is ever
// widened until a hand-authored orphan slips through, this test fails.

// ADR-0126 REPOINTED THIS PROBE, AND THE REASON MATTERS.
//
// It used to write `reference/core/architecture/zz-parity-probe-<pid>.md` and assert the
// suite failed on it. After the mandate narrowed to the seventeen-document entry surface,
// that path is deliberately released — so the probe stopped being caught, and the test
// failed for the right reason: it was pinning the OLD contract.
//
// Deleting it would have removed the only proof that the orphan check catches anything at
// all. So it now probes where the mandate still applies: an entry-surface document with its
// Spanish half temporarily moved aside. The rename is restored in `finally`, and the file is
// moved rather than deleted so a crashed run leaves it recoverable next to its original.
test('an entry-surface document that loses its Spanish half FAILS the guard', () => {
  const english = path.join(REPO_ROOT, 'reference/core/architecture/README.md');
  const spanish = path.join(REPO_ROOT, 'reference/core/architecture/README.es.md');
  assert.ok(fs.existsSync(english) && fs.existsSync(spanish),
    'fixture pair must exist — it is one of the seventeen entry-surface documents');

  const stashed = `${spanish}.stashed-by-test-${process.pid}`;
  fs.renameSync(spanish, stashed);
  try {
    const { code, out } = runGuard();
    assert.equal(code, 1, 'guard must fail on an unpaired ENTRY-SURFACE document');
    assert.match(out, /README\.es\.md/, 'the guard must NAME the missing counterpart');
  } finally {
    fs.renameSync(stashed, spanish);
  }
});

// The complement: outside the entry surface an orphan is released, not caught. Without
// this, a future change that quietly re-widened the scope would still pass the test above.
test('a hand-authored unpaired document OUTSIDE the entry surface is released (ADR-0126)', () => {
  const dir = path.join(REPO_ROOT, 'reference/core/architecture');
  const probe = path.join(dir, `zz-parity-probe-${process.pid}.md`);
  assert.ok(
    !GENERATED_DOC_EXCLUSIONS.some((e) => e.matches(path.relative(REPO_ROOT, probe).split(path.sep).join('/'))),
    'the probe path must not be covered by any exclusion, or this test proves nothing',
  );

  fs.writeFileSync(probe, '# Parity probe\n\nHand-authored, deliberately untranslated.\n');
  try {
    const { code } = runGuard();
    assert.equal(code, 0, 'an orphan outside the entry surface is released by ADR-0126, not caught');
  } finally {
    fs.rmSync(probe, { force: true });
  }
});

// The OKF bundle used to be count-pinned: its projector stamped nothing, so the only
// available proof was "the inventory is exactly 15 files" — which a hand-written file can
// satisfy just by displacing a generated one. The projector now stamps every document, so
// the entry is marker-verified like the others. These two tests are what keep it that way.

test('the OKF bundle exclusion is marker-verified, not count-pinned', () => {
  const okf = GENERATED_DOC_EXCLUSIONS.find((e) => e.id === 'knowledge-okf-bundle');
  assert.ok(okf, 'the knowledge-okf-bundle entry must exist');
  assert.equal(typeof okf.marker, 'string', 'membership must be proven per file, not by inventory count');
  assert.equal(okf.expectedFiles, undefined, 'a marker-verified entry must not also pin a count');

  const dir = path.join(REPO_ROOT, 'reference/knowledge/okf');
  const walk = (d) =>
    fs.readdirSync(d, { withFileTypes: true }).flatMap((e) =>
      e.isDirectory() ? walk(path.join(d, e.name)) : e.name.endsWith('.md') ? [path.join(d, e.name)] : [],
    );
  const files = walk(dir);
  assert.ok(files.length > 0, 'the published bundle must be on disk');
  for (const f of files) {
    assert.ok(
      fs.readFileSync(f, 'utf8').includes(okf.marker),
      `${path.relative(REPO_ROOT, f)} lacks the projector's provenance banner — regenerate the bundle`,
    );
  }
});

// ADR-0126 CHANGED WHAT THIS TEST CAN CLAIM, AND THE LOSS IS STATED RATHER THAN HIDDEN.
//
// Marker verification is intact: an unstamped intruder is still DETECTED, still NAMED, and
// still reported as kept in scope rather than inheriting a path-based exemption. That is the
// property this test was written for and it still holds.
//
// What no longer holds is the exit code. The orphan GATE now covers only the seventeen
// entry-surface documents, so an unpaired intruder in a generated tree is reported and does
// not fail the build. That is a real reduction in enforcement, accepted by ADR-0126 and
// written down here so the next reader does not mistake a green run for an empty report.
test('an unstamped file dropped into the OKF bundle is DETECTED and named, not silently exempted', () => {
  const probe = path.join(REPO_ROOT, 'reference/knowledge/okf', `zz-parity-probe-${process.pid}.md`);
  // Deliberately OKF-shaped: valid frontmatter, plausible location. Only the banner is missing.
  fs.writeFileSync(probe, '---\ntype: Concept\ntitle: Sneaked in\n---\n\n# Sneaked in\n\nHand-authored.\n');
  try {
    const { code, out } = runGuard();
    assert.equal(code, 0, 'ADR-0126: reported, but no longer a gate failure outside the entry surface');
    assert.match(out, new RegExp(path.basename(probe)), 'the guard must NAME the offending file');
    assert.match(out, /\[knowledge-okf-bundle\][\s\S]*do NOT carry the marker/);
    // And the real bundle keeps its exemption — one intruder must not nuke the whole entry.
    assert.match(out, /knowledge-okf-bundle: \d+ file\(s\)/);
  } finally {
    fs.rmSync(probe, { force: true });
  }
});

test('an unstamped file dropped into a generated tree is DETECTED, not path-exempted', () => {
  const probe = path.join(REPO_ROOT, 'reference/wiki', `zz-parity-probe-${process.pid}.md`);
  fs.writeFileSync(probe, '# Sneaked in\n\nNo generator banner. Must not be exempt.\n');
  try {
    const { code, out } = runGuard();
    assert.equal(code, 0, 'ADR-0126: reported, not a gate failure — path-based membership still must not exempt it');
    assert.match(out, new RegExp(path.basename(probe)));
    assert.match(out, /do NOT carry the marker/);
  } finally {
    fs.rmSync(probe, { force: true });
  }
});
