import assert from 'node:assert/strict';
import test from 'node:test';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import {
  GENERATED_DOC_EXCLUSIONS,
  validateEntries,
  partitionByExclusions,
  formatExclusionReport,
} from './generated-doc-exclusions.mjs';

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../..');
const SUITE = path.join(REPO_ROOT, '.harness/scripts/ci/suites/bilingual-suite.mjs');

/** Run the real guard and return { code, out }. */
function runGuard() {
  try {
    const out = execFileSync('node', [SUITE], { cwd: REPO_ROOT, encoding: 'utf8', stdio: 'pipe' });
    return { code: 0, out };
  } catch (err) {
    return { code: err.status ?? 1, out: `${err.stdout ?? ''}${err.stderr ?? ''}` };
  }
}

// --- The rules the table must obey -------------------------------------------

test('every declared exclusion names a generator and a reason', () => {
  assert.doesNotThrow(() => validateEntries());
  for (const e of GENERATED_DOC_EXCLUSIONS) {
    assert.ok(e.generator?.trim(), `${e.id} must name its generator`);
    assert.ok(e.reason?.trim(), `${e.id} must state why parity does not apply`);
  }
});

test('an exclusion without a generator is rejected, not silently accepted', () => {
  assert.throws(
    () => validateEntries([{ id: 'x', reason: 'because', matches: () => true, marker: 'm' }]),
    /has no `generator`/,
  );
});

test('an exclusion without a reason is rejected', () => {
  assert.throws(
    () => validateEntries([{ id: 'x', generator: 'g.mjs', matches: () => true, marker: 'm' }]),
    /has no `reason`/,
  );
});

test('an exclusion that proves membership neither by marker nor by pinned count is rejected', () => {
  assert.throws(
    () => validateEntries([{ id: 'x', generator: 'g.mjs', reason: 'r', matches: () => true }]),
    /neither `marker` nor `expectedFiles`/,
  );
});

// --- Membership is proven, not asserted --------------------------------------

test('a file inside a marker-verified tree that lacks the marker stays IN SCOPE', () => {
  const entries = [
    { id: 'wiki', generator: 'sync-wiki.mjs', reason: 'mirror', matches: (r) => r.startsWith('w/'), marker: 'AUTOGEN' },
  ];
  const files = ['w/real.md', 'w/handwritten.md'];
  const read = (r) => (r === 'w/real.md' ? 'AUTOGEN header\n' : 'I wrote this by hand\n');

  const p = partitionByExclusions(files, read, entries);
  assert.deepEqual(p.excluded[0].files, ['w/real.md']);
  assert.deepEqual(p.inScope, ['w/handwritten.md'], 'unstamped file must not be exempted');
  assert.match(p.refusals.join('\n'), /do NOT carry the marker/);
});

test('a count-pinned tree that changed shape has its exclusion REFUSED entirely', () => {
  const entries = [
    { id: 'okf', generator: 'okf.mjs', reason: 'projection', matches: (r) => r.startsWith('okf/'), expectedFiles: 2 },
  ];
  const p = partitionByExclusions(['okf/a.md', 'okf/b.md', 'okf/surprise.md'], () => '', entries);
  assert.deepEqual(p.excluded[0].files, [], 'refused exclusion exempts nothing');
  assert.equal(p.inScope.length, 3, 'all files fall back into scope so the guard goes red');
  assert.match(p.refusals.join('\n'), /EXCLUSION REFUSED/);
});

// --- Exclusions are reported, never hidden -----------------------------------

test('the report names each exclusion, its count, its generator and its reason', () => {
  const entries = [
    { id: 'wiki', generator: 'sync-wiki.mjs', reason: 'published mirror', matches: (r) => r.startsWith('w/'), marker: 'AUTOGEN' },
  ];
  const report = formatExclusionReport(partitionByExclusions(['w/a.md'], () => 'AUTOGEN', entries));
  assert.match(report, /1 file\(s\) exempt/);
  assert.match(report, /wiki: 1 file\(s\)/);
  assert.match(report, /generated by sync-wiki\.mjs/);
  assert.match(report, /published mirror/);
});

test('the live guard prints its exclusion ledger on every run', () => {
  const { out } = runGuard();
  assert.match(out, /declared exclusions \(\d+ file\(s\) exempt/);
  for (const e of GENERATED_DOC_EXCLUSIONS) {
    assert.match(out, new RegExp(`${e.id}: \\d+ file\\(s\\)`), `${e.id} must appear in the ledger`);
  }
});

// --- THE POINT: the guard still catches a genuine unpaired document ----------
//
// This is the regression the whole change exists to protect. If an exclusion is ever
// widened until a hand-authored orphan slips through, this test fails.

test('a hand-authored unpaired document under a non-excluded reference/ path FAILS the guard', () => {
  const dir = path.join(REPO_ROOT, 'reference/core/architecture');
  assert.ok(fs.existsSync(dir), 'fixture directory must exist and must not be excluded');
  const probe = path.join(dir, `zz-parity-probe-${process.pid}.md`);
  assert.ok(
    !GENERATED_DOC_EXCLUSIONS.some((e) => e.matches(path.relative(REPO_ROOT, probe).split(path.sep).join('/'))),
    'the probe path must not be covered by any exclusion, or this test proves nothing',
  );

  fs.writeFileSync(probe, '# Parity probe\n\nHand-authored, deliberately untranslated.\n');
  try {
    const { code, out } = runGuard();
    assert.equal(code, 1, 'guard must fail on an unpaired hand-authored document');
    assert.match(out, new RegExp(path.basename(probe)), 'the guard must NAME the offending file');
  } finally {
    fs.rmSync(probe, { force: true });
  }
});

test('an unstamped file dropped into a generated tree FAILS the guard rather than inheriting its exemption', () => {
  const probe = path.join(REPO_ROOT, 'reference/wiki', `zz-parity-probe-${process.pid}.md`);
  fs.writeFileSync(probe, '# Sneaked in\n\nNo generator banner. Must not be exempt.\n');
  try {
    const { code, out } = runGuard();
    assert.equal(code, 1, 'path-based membership alone must not exempt a file');
    assert.match(out, new RegExp(path.basename(probe)));
    assert.match(out, /do NOT carry the marker/);
  } finally {
    fs.rmSync(probe, { force: true });
  }
});
